### PR TITLE
Update to php-7.4.0

### PR DESCRIPTION
**Pull request by nick-zh**

### CODE REVIEW

**Comment by nick-zh** [comment]
@tianon please let me know if this is ok :+1:

**Comment by tianon** [comment]
At a glance this looks good, I think we need to also update `generate-stackbrew-library.sh` (we're all on PTO now -- it's not just a holiday but it's one of the Big Four US holidays 😅)

**Comment by nick-zh** [comment]
@tianon thanks a lot, i totally missed that and adjusted accordingly. Very sry to have pinged you on a holiday :bowing_man: i was just super excited and wanted to help out. Happy thanksgiving and have a great day! :turkey:

**Comment by JoelLinn** [comment]
Shouldn’t we squash(fixup) those two commits?

**Comment by nick-zh** [comment]
I guess they squash merge the branch anyway.
I am not sure about the pkg-config thing, but i am sure after thanksgiving we'll get some feedback on that

**Comment by thaJeztah** [comment]
> I guess they squash merge the branch anyway.

Not sure if they do, but if they do; I noticed you GPG signed your commits; that will be lost when the GitHub squash and merge feature is used.

**Comment by tianon** [comment]
> Very sry to have pinged you on a holiday  i was just super excited and wanted to help out. Happy thanksgiving and have a great day!

Don't worry about it in the slightest -- it's my own fault for checking email! :smile:
(It's definitely an odd time for the upstream release, given the potential for downstream delays, but such is life. :smile:)

I've got a few minutes this morning to look this over, and it all looks great, thanks!  I'm not worried about two commits. :+1:

**Comment by nick-zh** [comment]
@tianon thank you very much for taking the time!

**Pull request merged**
