### PR TITLE
Adjust "docker-php-ext-configure" to also install deps, but have "docker-php-ext-install" remove them if and only if it was "docker-php-ext-*" which installed them.

### PR DESCRIPTION
**Pull request by tianon**
Closes #237

### CODE REVIEW

**Comment by shouze** [comment]
Looks great! Very good yet simple optimization

**Comment by yosifkit** [comment]
LGTM

**Comment by yosifkit** [comment]
Can you run `update.sh`?

**Comment by shouze** [comment]
@tianon I've made your the PR for the run of `update.sh` https://github.com/infosiftr/php/pull/1 ;)

**Comment by tianon** [comment]
Thanks :smile:

Once Travis is green, we're good to merge! :+1:

**Pull request merged**
