### PR TITLE
Apache with PHP 7.2/7.3 in Alpine 3.8/3.9

### PR DESCRIPTION
**Pull request by mrtimp**
@mivanovaxway as discussed here is a proposed PR to support Apache with PHP 7.2/7.3 in current Alpine versions.  

I had a look at the a2enmod/a2dismod and while they look easy to port it will require refactoring the Apache configuration that comes with Alpine.

### CODE REVIEW

**Comment by mrtimp** [comment]
@mivanovaxway have you had any free time to test the new Apache images?

**Comment by mrtimp** [comment]
@mivanovaxway how did you get on testing the new Apache images?  I would be keen to know if there is interest merging this PR.

**Comment by lubo** [comment]
@tianon and @yosifkit seem to be maintainers here. I'd be great if this got merged, since #259 states good reasons why having this variant would be beneficial.

**Comment by mrtimp** [comment]
Thanks for your support @lubo. I look forward to feedback from the maintainers :-)

**Comment by mrtimp** [comment]
@tianon / @yosifkit do you have any thoughts on this PR or another maintainer who might be interested in its value?

**Comment by mivanovaxway** [comment]
@mrtimp I've forked your branch and updated the versions for alpine{3.8-3.9}-apache to 7.2.19 and 7.3.6 respectively. I am building the alpine3.9+apache+php7.2.19 and the alpine3.9+apache+php7.3.6 images and will post here after I do some tests with them.

**Comment by tianon** [comment]
I want to preface by saying this work is really interesting, and I hope I can articulate our position on supporting this in such a way that isn't discouraging (on the contrary, I'd love to see this grow). :heart:

My primary concerns with this are first and foremost the added maintenance burden of updating, supporting, building, debugging, etc. and second the delta from our existing Apache variants (in contrast, the `cli` and `fpm` variants are roughly fully interchangeable with minimal effort).  The second of those is something that's theoretically possible to resolve (as you've already noted), but at a significantly added expense to the first.

In addition, I've some worry of adding more Alpine variants given that we've seen issues with Alpine support in PHP and there's not really any official statement from the PHP upstream project one way or another as to whether Alpine and/or musl is really something they support.

What I would encourage is to do something like https://github.com/mlocati/docker-php-extension-installer and maintain this externally for interested users (and hopefully this PR can serve as a method of traffic redirection for such an effort to help those interested users locate it).  I think the overall changes to our `./configure` arguments, etc are typically infrequent enough that it shouldn't be too difficult to track them and focus on maintaining the Apache-on-Alpine experience.

**Comment by mrtimp** [comment]
Thanks for the feedback @tianon 

I quite often find that PR's on other projects are ignored/closed leaving the person who raised the PR with questions as to why, you've gone into details of the projects vision here which provides me the detail on why this PR might not be ideal for this project. On top of that you've gone above by providing suggestions on how we may be able to share this with the community but in a slightly different format. Thank you for that.

I will have a think about potential next steps.  Thanks again :-)

**Pull request closed without merging**
