### PR TITLE
Convert all Dockerfiles to be template-based, and resync a few minor bits of Alpine and Debian (libedit in both, no recode in either, POSIX shell versions of docker-php-ext-* scripts for all)

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Stalled on https://github.com/docker-library/official-images/pull/1553 -- will restart Travis once that settles

**Comment by tianon** [comment]
GREEEEEEEEEEN

**Comment by tianon** [comment]
Just the meaningful bits:
```diff
diff --git a/.travis.yml b/.travis.yml
index c67b3aa..2e37a83 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,17 +3,26 @@ services: docker
 
 env:
   - VERSION=7.0 VARIANT=
+  - VERSION=7.0 VARIANT=alpine
   - VERSION=7.0 VARIANT=apache
   - VERSION=7.0 VARIANT=fpm
+  - VERSION=7.0 VARIANT=fpm/alpine
   - VERSION=7.0 VARIANT=zts
+  - VERSION=7.0 VARIANT=zts/alpine
   - VERSION=5.6 VARIANT=
+  - VERSION=5.6 VARIANT=alpine
   - VERSION=5.6 VARIANT=apache
   - VERSION=5.6 VARIANT=fpm
+  - VERSION=5.6 VARIANT=fpm/alpine
   - VERSION=5.6 VARIANT=zts
+  - VERSION=5.6 VARIANT=zts/alpine
   - VERSION=5.5 VARIANT=
+  - VERSION=5.5 VARIANT=alpine
   - VERSION=5.5 VARIANT=apache
   - VERSION=5.5 VARIANT=fpm
+  - VERSION=5.5 VARIANT=fpm/alpine
   - VERSION=5.5 VARIANT=zts
+  - VERSION=5.5 VARIANT=zts/alpine
 
 install:
   - git clone https://github.com/docker-library/official-images.git ~/official-images
@@ -22,6 +31,7 @@ before_script:
   - env | sort
   - cd "$VERSION"
   - image="php:${VERSION}${VARIANT:+-$VARIANT}"
+  - image="${image//'/'/-}"
 
 script:
   - docker build -t "$image" "${VARIANT:-.}"
diff --git a/7.0/Dockerfile b/7.0/Dockerfile
index 1a1f31c..9df465c 100644
--- a/7.0/Dockerfile
+++ b/7.0/Dockerfile
@@ -1,10 +1,25 @@
 FROM debian:jessie
 
-# persistent / runtime deps
-RUN apt-get update && apt-get install -y ca-certificates curl librecode0 libsqlite3-0 libxml2 --no-install-recommends && rm -r /var/lib/apt/lists/*
-
 # phpize deps
-RUN apt-get update && apt-get install -y autoconf file g++ gcc libc-dev make pkg-config re2c --no-install-recommends && rm -r /var/lib/apt/lists/*
+RUN apt-get update && apt-get install -y \
+		autoconf \
+		file \
+		g++ \
+		gcc \
+		libc-dev \
+		make \
+		pkg-config \
+		re2c \
+	--no-install-recommends && rm -r /var/lib/apt/lists/*
+
+# persistent / runtime deps
+RUN apt-get update && apt-get install -y \
+		ca-certificates \
+		curl \
+		libedit2 \
+		libsqlite3-0 \
+		libxml2 \
+	--no-install-recommends && rm -r /var/lib/apt/lists/*
 
 ENV PHP_INI_DIR /usr/local/etc/php
 RUN mkdir -p $PHP_INI_DIR/conf.d
@@ -13,52 +28,51 @@ RUN mkdir -p $PHP_INI_DIR/conf.d
 ##</autogenerated>##
 
 ENV GPG_KEYS 1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763
-RUN set -xe \
-	&& for key in $GPG_KEYS; do \
-		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
-	done
 
 ENV PHP_VERSION 7.0.4
 ENV PHP_FILENAME php-7.0.4.tar.xz
 ENV PHP_SHA256 584e0e374e357a71b6e95175a2947d787453afc7f9ab7c55651c10491c4df532
 
-# --enable-mysqlnd is included below because it's harder to compile after the fact the extensions are (since it's a plugin for several extensions, not an extension in itself)
-RUN buildDeps=" \
+RUN set -xe \
+	&& buildDeps=" \
 		$PHP_EXTRA_BUILD_DEPS \
 		libcurl4-openssl-dev \
-		libreadline6-dev \
-		librecode-dev \
+		libedit-dev \
 		libsqlite3-dev \
 		libssl-dev \
 		libxml2-dev \
 		xz-utils \
 	" \
-	&& set -x \
 	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
 	&& curl -fSL "http://php.net/get/$PHP_FILENAME/from/this/mirror" -o "$PHP_FILENAME" \
 	&& echo "$PHP_SHA256 *$PHP_FILENAME" | sha256sum -c - \
 	&& curl -fSL "http://php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o "$PHP_FILENAME.asc" \
+	&& export GNUPGHOME="$(mktemp -d)" \
+	&& for key in $GPG_KEYS; do \
+		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+	done \
 	&& gpg --batch --verify "$PHP_FILENAME.asc" "$PHP_FILENAME" \
+	&& rm -r "$GNUPGHOME" "$PHP_FILENAME.asc" \
 	&& mkdir -p /usr/src/php \
 	&& tar -xf "$PHP_FILENAME" -C /usr/src/php --strip-components=1 \
-	&& rm "$PHP_FILENAME"* \
+	&& rm "$PHP_FILENAME" \
 	&& cd /usr/src/php \
 	&& ./configure \
 		--with-config-file-path="$PHP_INI_DIR" \
 		--with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
 		$PHP_EXTRA_CONFIGURE_ARGS \
 		--disable-cgi \
+# --enable-mysqlnd is included here because it's harder to compile after the fact than extensions are (since it's a plugin for several extensions, not an extension in itself)
 		--enable-mysqlnd \
 		--with-curl \
+		--with-libedit \
 		--with-openssl \
-		--with-readline \
-		--with-recode \
 		--with-zlib \
 	&& make -j"$(nproc)" \
 	&& make install \
 	&& { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } \
-	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps \
-	&& make clean
+	&& make clean \
+	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps
 
 COPY docker-php-ext-* /usr/local/bin/
 
diff --git a/7.0/alpine/Dockerfile b/7.0/alpine/Dockerfile
index d035877..e0ef122 100644
--- a/7.0/alpine/Dockerfile
+++ b/7.0/alpine/Dockerfile
@@ -1,53 +1,74 @@
 FROM alpine:3.3
 
+# phpize deps
+RUN apk add --no-cache --virtual .phpize-deps \
+		autoconf \
+		file \
+		g++ \
+		gcc \
+		libc-dev \
+		make \
+		pkgconf \
+		re2c
+
+# persistent / runtime deps
+RUN apk add --no-cache --virtual .persistent-deps \
+		ca-certificates \
+		curl
+
+# ensure www-data user exists
+RUN set -x \
+	&& addgroup -g 82 -S www-data \
+	&& adduser -u 82 -D -S -G www-data www-data
+# 82 is the standard uid/gid for "www-data" in Alpine
+# http://git.alpinelinux.org/cgit/aports/tree/main/apache2/apache2.pre-install?h=v3.3.2
+# http://git.alpinelinux.org/cgit/aports/tree/main/lighttpd/lighttpd.pre-install?h=v3.3.2
+# http://git.alpinelinux.org/cgit/aports/tree/main/nginx-initscripts/nginx-initscripts.pre-install?h=v3.3.2
+
 ENV PHP_INI_DIR /usr/local/etc/php
 RUN mkdir -p $PHP_INI_DIR/conf.d
 
-ENV PHP_VERSION 7.0.4
-ENV PHP_FILENAME php-7.0.4.tar.xz
-ENV PHP_SHA256 584e0e374e357a71b6e95175a2947d787453afc7f9ab7c55651c10491c4df532
-
 ##<autogenerated>##
 ##</autogenerated>##
 
-# --enable-mysqlnd is included below because it's harder to compile after the fact the extensions are (since it's a plugin for several extensions, not an extension in itself)
 ENV GPG_KEYS 1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763
+
+ENV PHP_VERSION 7.0.4
+ENV PHP_FILENAME php-7.0.4.tar.xz
+ENV PHP_SHA256 584e0e374e357a71b6e95175a2947d787453afc7f9ab7c55651c10491c4df532
+
 RUN set -xe \
 	&& apk add --no-cache --virtual .build-deps \
-		autoconf \
 		curl-dev \
-		file \
-		gcc \
 		gnupg \
-		libc-dev \
 		libedit-dev \
 		libxml2-dev \
-		make \
 		openssl-dev \
-		pkgconf \
-		re2c \
 		sqlite-dev \
-	&& for key in $GPG_KEYS; do \
-		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
-	done \
 	&& curl -fSL "http://php.net/get/$PHP_FILENAME/from/this/mirror" -o "$PHP_FILENAME" \
 	&& echo "$PHP_SHA256 *$PHP_FILENAME" | sha256sum -c - \
 	&& curl -fSL "http://php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o "$PHP_FILENAME.asc" \
+	&& export GNUPGHOME="$(mktemp -d)" \
+	&& for key in $GPG_KEYS; do \
+		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+	done \
 	&& gpg --batch --verify "$PHP_FILENAME.asc" "$PHP_FILENAME" \
+	&& rm -r "$GNUPGHOME" "$PHP_FILENAME.asc" \
 	&& mkdir -p /usr/src \
 	&& tar -Jxf "$PHP_FILENAME" -C /usr/src \
-	&& mv /usr/src/php-$PHP_VERSION /usr/src/php \
-	&& rm "$PHP_FILENAME"* \
+	&& mv "/usr/src/php-$PHP_VERSION" /usr/src/php \
+	&& rm "$PHP_FILENAME" \
 	&& cd /usr/src/php \
 	&& ./configure \
 		--with-config-file-path="$PHP_INI_DIR" \
 		--with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
 		$PHP_EXTRA_CONFIGURE_ARGS \
 		--disable-cgi \
+# --enable-mysqlnd is included here because it's harder to compile after the fact than extensions are (since it's a plugin for several extensions, not an extension in itself)
 		--enable-mysqlnd \
 		--with-curl \
-		--with-openssl \
 		--with-libedit \
+		--with-openssl \
 		--with-zlib \
 	&& make -j"$(getconf _NPROCESSORS_ONLN)" \
 	&& make install \
diff --git a/7.0/alpine/docker-php-ext-enable b/7.0/alpine/docker-php-ext-enable
index 5381d0d..367aaf2 100755
--- a/7.0/alpine/docker-php-ext-enable
+++ b/7.0/alpine/docker-php-ext-enable
@@ -4,15 +4,37 @@ set -e
 cd "$(php -r 'echo ini_get("extension_dir");')"
 
 usage() {
-	echo "usage: $0 module-name [module-name ...]"
+	echo "usage: $0 [options] module-name [module-name ...]"
 	echo "   ie: $0 gd mysqli"
 	echo "       $0 pdo pdo_mysql"
+	echo "       $0 --ini-name 0-apc.ini apcu apc"
 	echo
 	echo 'Possible values for module-name:'
 	echo $(find -maxdepth 1 -type f -name '*.so' -exec basename '{}' ';' | sort)
 }
 
-modules=""
+opts="$(getopt -o 'h?' --long 'help,ini-name:' -- "$@" || { usage >&2 && false; })"
+eval set -- "$opts"
+
+iniName=
+while true; do
+	flag="$1"
+	shift
+	case "$flag" in
+		--help|-h|'-?') usage && exit 0 ;;
+		--ini-name) iniName="$1" && shift ;;
+		--) break ;;
+		*)
+			{
+				echo "error: unknown flag: $flag"
+				usage
+			} >&2
+			exit 1
+			;;
+	esac
+done
+
+modules=
 for module; do
 	if [ -z "$module" ]; then
 		continue
@@ -35,8 +57,8 @@ if [ -z "$modules" ]; then
 	exit 1
 fi
 
-for module in ${modules}; do
-	if grep -q zend_extension_entry "$module"; then
+for module in $modules; do
+	if nm -g "$module" | grep -q ' zend_extension_entry$'; then
 		# https://wiki.php.net/internals/extensions#loading_zend_extensions
 		line="zend_extension=$(readlink -f "$module")"
 	else
@@ -54,7 +76,7 @@ for module in ${modules}; do
 		continue
 	fi
 
-	ini="/usr/local/etc/php/conf.d/docker-php-ext-$ext.ini"
+	ini="/usr/local/etc/php/conf.d/${iniName:-"docker-php-ext-$ext.ini"}"
 	if ! grep -q "$line" "$ini" 2>/dev/null; then
 		echo "$line" >> "$ini"
 	fi
diff --git a/7.0/alpine/docker-php-ext-install b/7.0/alpine/docker-php-ext-install
index 68309ff..67180a8 100755
--- a/7.0/alpine/docker-php-ext-install
+++ b/7.0/alpine/docker-php-ext-install
@@ -61,7 +61,11 @@ for ext in $exts; do
 		[ -e Makefile ] || docker-php-ext-configure "$ext"
 		make -j"$j"
 		make -j"$j" install
-		ls modules/*.so | cut -d/ -f2 | xargs -r docker-php-ext-enable
+		find modules \
+			-maxdepth 1 \
+			-name '*.so' \
+			-exec basename '{}' ';' \
+				| xargs -r docker-php-ext-enable
 		make -j"$j" clean
 	)
 done
diff --git a/7.0/docker-php-ext-configure b/7.0/docker-php-ext-configure
index 3d21b5b..39947c8 100755
--- a/7.0/docker-php-ext-configure
+++ b/7.0/docker-php-ext-configure
@@ -1,9 +1,9 @@
-#!/bin/bash
+#!/bin/sh
 set -e
 
 ext="$1"
 extDir="/usr/src/php/ext/$ext"
-if [ -z "$ext" -o ! -d "$extDir" ]; then
+if [ -z "$ext" ] || ! [ -d "$extDir" ]; then
 	echo >&2 "usage: $0 ext-name [configure flags]"
 	echo >&2 "   ie: $0 gd --with-jpeg-dir=/usr/local/something"
 	echo >&2
diff --git a/7.0/docker-php-ext-enable b/7.0/docker-php-ext-enable
index edb07ed..367aaf2 100755
--- a/7.0/docker-php-ext-enable
+++ b/7.0/docker-php-ext-enable
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 set -e
 
 cd "$(php -r 'echo ini_get("extension_dir");')"
@@ -34,32 +34,30 @@ while true; do
 	esac
 done
 
-modules=()
-while [ $# -gt 0 ]; do
-	module="$1"
-	shift
+modules=
+for module; do
 	if [ -z "$module" ]; then
 		continue
 	fi
-	if [ -f "$module.so" -a ! -f "$module" ]; then
+	if [ -f "$module.so" ] && ! [ -f "$module" ]; then
 		# allow ".so" to be optional
-		module+='.so'
+		module="$module.so"
 	fi
-	if [ ! -f "$module" ]; then
+	if ! [ -f "$module" ]; then
 		echo >&2 "error: $(readlink -f "$module") does not exist"
 		echo >&2
 		usage >&2
 		exit 1
 	fi
-	modules+=( "$module" )
+	modules="$modules $module"
 done
 
-if [ "${#modules[@]}" -eq 0 ]; then
+if [ -z "$modules" ]; then
 	usage >&2
 	exit 1
 fi
 
-for module in "${modules[@]}"; do
+for module in $modules; do
 	if nm -g "$module" | grep -q ' zend_extension_entry$'; then
 		# https://wiki.php.net/internals/extensions#loading_zend_extensions
 		line="zend_extension=$(readlink -f "$module")"
diff --git a/7.0/docker-php-ext-install b/7.0/docker-php-ext-install
index 2c488cc..67180a8 100755
--- a/7.0/docker-php-ext-install
+++ b/7.0/docker-php-ext-install
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 set -e
 
 cd /usr/src/php/ext
@@ -36,10 +36,8 @@ while true; do
 	esac
 done
 
-exts=()
-while [ $# -gt 0 ]; do
-	ext="$1"
-	shift
+exts=
+for ext; do
 	if [ -z "$ext" ]; then
 		continue
 	fi
@@ -49,21 +47,25 @@ while [ $# -gt 0 ]; do
 		usage >&2
 		exit 1
 	fi
-	exts+=( "$ext" )
+	exts="$exts $ext"
 done
 
-if [ "${#exts[@]}" -eq 0 ]; then
+if [ -z "$exts" ]; then
 	usage >&2
 	exit 1
 fi
 
-for ext in "${exts[@]}"; do
+for ext in $exts; do
 	(
 		cd "$ext"
 		[ -e Makefile ] || docker-php-ext-configure "$ext"
 		make -j"$j"
 		make -j"$j" install
-		find modules -maxdepth 1 -name '*.so' -exec basename '{}' ';' | xargs --no-run-if-empty --verbose docker-php-ext-enable
+		find modules \
+			-maxdepth 1 \
+			-name '*.so' \
+			-exec basename '{}' ';' \
+				| xargs -r docker-php-ext-enable
 		make -j"$j" clean
 	)
 done
diff --git a/update.sh b/update.sh
index 087c2f0..cd600f6 100755
--- a/update.sh
+++ b/update.sh
@@ -63,18 +63,37 @@ for version in "${versions[@]}"; do
 		exit 1
 	fi
 	
-	( set -x; cp docker-php-ext-* "$version/" )
+	dockerfiles=()
 	
-	for variant in apache fpm zts; do
-		echo "Generating $version/$variant/Dockerfile from $variant-Dockerfile-block-*"
+	cp -v Dockerfile-debian.template "$version/Dockerfile"
+	cp -v docker-php-ext-* "$version/"
+	dockerfiles+=( "$version/Dockerfile" )
+	
+	if [ -d "$version/alpine" ]; then
+		cp -v Dockerfile-alpine.template "$version/alpine/Dockerfile"
+		cp -v docker-php-ext-* "$version/alpine/"
+		dockerfiles+=( "$version/alpine/Dockerfile" )
+	fi
+	
+	for target in apache fpm zts fpm/alpine zts/alpine; do
+		[ -d "$version/$target" ] || continue
+		base="$version/Dockerfile"
+		variant="${target%%/*}"
+		if [ "$target" != "$variant" ]; then
+			variantVariant="${target#$variant/}"
+			[ -d "$version/$variantVariant" ] || continue
+			base="$version/$variantVariant/Dockerfile"
+		fi
+		echo "Generating $version/$target/Dockerfile from $base + $variant-Dockerfile-block-*"
 		awk '
 			$1 == "##</autogenerated>##" { ia = 0 }
 			!ia { print }
 			$1 == "##<autogenerated>##" { ia = 1; ab++; ac = 0 }
 			ia { ac++ }
 			ia && ac == 1 { system("cat '$variant'-Dockerfile-block-" ab) }
-		' "$version/Dockerfile" > "$version/$variant/Dockerfile"
-		( set -x; cp docker-php-ext-* "$version/$variant/" )
+		' "$base" > "$version/$target/Dockerfile"
+		cp -v docker-php-ext-* "$version/$target/"
+		dockerfiles+=( "$version/$target/Dockerfile" )
 	done
 	
 	if [ -z "$fullVersion" ]; then
@@ -85,10 +104,10 @@ for version in "${versions[@]}"; do
 	(
 		set -x
 		sed -ri '
-			s/^(ENV PHP_VERSION) .*/\1 '"$fullVersion"'/;
-			s/^(ENV PHP_FILENAME) .*/\1 '"$filename"'/;
-			s/^(ENV PHP_SHA256) .*/\1 '"$sha256"'/;
-			s/^(ENV GPG_KEYS) [0-9a-fA-F ]*$/\1 '"$gpgKey"'/;
-		' "$version/Dockerfile" "$version/"*/Dockerfile
+			s!%%PHP_VERSION%%!'"$fullVersion"'!;
+			s!%%PHP_FILENAME%%!'"$filename"'!;
+			s!%%PHP_SHA256%%!'"$sha256"'!;
+			s!%%GPG_KEYS%%!'"$gpgKey"'!;
+		' "${dockerfiles[@]}"
 	)
 done
```

**Comment by tianon** [comment]
Another useful diff:
```diff
diff --git a/Dockerfile-alpine.template b/Dockerfile-debian.template
index 391f0fb..4d453d9 100644
--- a/Dockerfile-alpine.template
+++ b/Dockerfile-debian.template
@@ -1,29 +1,25 @@
-FROM alpine:3.3
+FROM debian:jessie
 
 # phpize deps
-RUN apk add --no-cache --virtual .phpize-deps \
+RUN apt-get update && apt-get install -y \
 		autoconf \
 		file \
 		g++ \
 		gcc \
 		libc-dev \
 		make \
-		pkgconf \
-		re2c
+		pkg-config \
+		re2c \
+	--no-install-recommends && rm -r /var/lib/apt/lists/*
 
 # persistent / runtime deps
-RUN apk add --no-cache --virtual .persistent-deps \
+RUN apt-get update && apt-get install -y \
 		ca-certificates \
-		curl
-
-# ensure www-data user exists
-RUN set -x \
-	&& addgroup -g 82 -S www-data \
-	&& adduser -u 82 -D -S -G www-data www-data
-# 82 is the standard uid/gid for "www-data" in Alpine
-# http://git.alpinelinux.org/cgit/aports/tree/main/apache2/apache2.pre-install?h=v3.3.2
-# http://git.alpinelinux.org/cgit/aports/tree/main/lighttpd/lighttpd.pre-install?h=v3.3.2
-# http://git.alpinelinux.org/cgit/aports/tree/main/nginx-initscripts/nginx-initscripts.pre-install?h=v3.3.2
+		curl \
+		libedit2 \
+		libsqlite3-0 \
+		libxml2 \
+	--no-install-recommends && rm -r /var/lib/apt/lists/*
 
 ENV PHP_INI_DIR /usr/local/etc/php
 RUN mkdir -p $PHP_INI_DIR/conf.d
@@ -38,13 +34,16 @@ ENV PHP_FILENAME %%PHP_FILENAME%%
 ENV PHP_SHA256 %%PHP_SHA256%%
 
 RUN set -xe \
-	&& apk add --no-cache --virtual .build-deps \
-		curl-dev \
-		gnupg \
+	&& buildDeps=" \
+		$PHP_EXTRA_BUILD_DEPS \
+		libcurl4-openssl-dev \
 		libedit-dev \
+		libsqlite3-dev \
+		libssl-dev \
 		libxml2-dev \
-		openssl-dev \
-		sqlite-dev \
+		xz-utils \
+	" \
+	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
 	&& curl -fSL "http://php.net/get/$PHP_FILENAME/from/this/mirror" -o "$PHP_FILENAME" \
 	&& echo "$PHP_SHA256 *$PHP_FILENAME" | sha256sum -c - \
 	&& curl -fSL "http://php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o "$PHP_FILENAME.asc" \
@@ -54,9 +53,8 @@ RUN set -xe \
 	done \
 	&& gpg --batch --verify "$PHP_FILENAME.asc" "$PHP_FILENAME" \
 	&& rm -r "$GNUPGHOME" "$PHP_FILENAME.asc" \
-	&& mkdir -p /usr/src \
-	&& tar -Jxf "$PHP_FILENAME" -C /usr/src \
-	&& mv "/usr/src/php-$PHP_VERSION" /usr/src/php \
+	&& mkdir -p /usr/src/php \
+	&& tar -xf "$PHP_FILENAME" -C /usr/src/php --strip-components=1 \
 	&& rm "$PHP_FILENAME" \
 	&& cd /usr/src/php \
 	&& ./configure \
@@ -70,19 +68,11 @@ RUN set -xe \
 		--with-libedit \
 		--with-openssl \
 		--with-zlib \
-	&& make -j"$(getconf _NPROCESSORS_ONLN)" \
+	&& make -j"$(nproc)" \
 	&& make install \
-	&& { find /usr/local/bin /usr/local/sbin -type f -perm +0111 -exec strip --strip-all '{}' + || true; } \
+	&& { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } \
 	&& make clean \
-	&& runDeps="$( \
-		scanelf --needed --nobanner --recursive /usr/local \
-			| awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
-			| sort -u \
-			| xargs -r apk info --installed \
-			| sort -u \
-	)" \
-	&& apk add --virtual .php-rundeps $runDeps \
-	&& apk del .build-deps
+	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps
 
 COPY docker-php-ext-* /usr/local/bin/
 
```

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
