### PR TITLE
Updated Alpine version to 3.6 for PHP 7.1

### PR DESCRIPTION
**Pull request by elegos**
This pull request updates the Alpine version to 3.6 for PHP 7.1 images.

### CODE REVIEW

**Comment by tianon** [comment]
See also #357, #360, and docker-library/golang#131 (comment) for where a similar change was made previously, where it was reverted, and the discussion that led to the revert. :disappointed:

**Comment by elegos** [comment]
@tianon: uhm, maybe we could create a new tag? I mean, I need Alpine >= 3.5 due to new packages in the repositories (in particular: shadow). I can of course continue using giacomofurlan/php (my public docker hub repo), but it'd be a pity not to include it in the main one.

Thanks :)

**Comment by greut** [comment]
golang creates images for alpine 3.4, 3.5 and 3.6. https://hub.docker.com/_/golang/

**Comment by Soullivaneuh** [comment]
> golang creates images for alpine 3.4, 3.5 and 3.6. https://hub.docker.com/_/golang/

This is a good alternative solution.

Also, this should be dispatched to 7.0 too, and maybe 5.6.

**Comment by tianon** [comment]
The thing that makes that solution more palpable for "golang" is that
"golang" only has two supported versions, and for each supported version,
we only support "jessie"/"stretch" and "alpine3.4"/"alpine3.6" variants, so
the full list of uniq supported tags (and thus Dockerfiles) is only 11,
even with added Alpine variants.

In the case of PHP, that number is _currently_ 28.  There are four
supported versions of PHP, and each version has at least seven supported
variants/configurations.  Additionally, "golang" builds relatively quickly
while "php" does not.

**Comment by tianon** [comment]
Additionally, even if we only do this for a single version (say, 7.1), it will add at least 3 new variants (since we support `php:7.1-alpine`, `php:7.1-fpm-alpine`, and `php:7.1-zts-alpine`).

**Comment by Soullivaneuh** [comment]
> In the case of PHP, that number is _currently_ 28.  There are four
supported versions of PHP, and each version has at least seven supported
variants/configurations.

Maybe time for scripting a little bit more? :smile: Example: https://github.com/nexylan/docker-php-dev/blob/36ccdfc5ddabd3e2074a7bee43c3dc8bf399e64d/update.sh

> Additionally, "golang" builds relatively quickly
while "php" does not.

Well, maybe this can be improved but it's not a big problem IMHO.

**Comment by yosifkit** [comment]
Closing in favor of discussion to create base distro update process https://github.com/docker-library/php/issues/504.

**Pull request closed without merging**
