### PR TITLE
update alpine from 3.4 to 3.5

### PR DESCRIPTION
**Pull request by billyplus**
can't install php7-pdo_mysql on alpine 3.4.
so i have update to 3.5, and switch openssl to libressl

### CODE REVIEW

**Comment by tianon** [comment]
See also https://github.com/docker-library/php/pull/357, https://github.com/docker-library/php/pull/360, and https://github.com/docker-library/golang/pull/131#issuecomment-270677556 for where this change was made previously, where it was reverted, and the discussion that led to the revert. :disappointed:

**Comment by billyplus** [comment]
how about php:alpine is from alpine latest, and php:7.1-alpine is from alpine 3.4

**Comment by ellisio** [comment]
You don't want to do that because then you're breaking the versioning scheme of the PHP Docker images.

**Comment by shouze** [comment]
Ok as alpine 3.6 has been released since and that node 8.1 alpine images are alpine 3.6 based, I think it's time to go for php images too, no? ping @tianon

**Comment by yosifkit** [comment]
Alpine 3.6 will happen with the bump to php 7.2: https://github.com/docker-library/php/pull/448.

**Comment by shouze** [comment]
ok so @billyplus would you plz close this PR? #448 supersedes yours.

**Pull request closed without merging**
