### PR TITLE
Bump PHP 7.0 to RC2

### PR DESCRIPTION
**Pull request by andrerom**
:ship:

### CODE REVIEW

**Comment by skyred** [comment]
@andrerom Please squash the commits as suggested here https://github.com/docker-library/php/pull/127#issuecomment-133697948

**Comment by andrerom** [comment]
Ok, I'll rebase :)

**Comment by andrerom** [comment]
Ok, Rebased now :)

**Comment by thaJeztah** [comment]
Great! thanks @andrerom, and thanks @skyred for assisting, much appreciated :+1:

ping @tianon @yosifkit :-)

**Comment by tianon** [comment]
LGTM

**Comment by randall210** [comment]
LCD

**Pull request merged**
