### PR TITLE
Ensure PHP-FPM worker stdout and stderr are sent to the main error log.

### LINKED ISSUE #140: Can't send PHP errors to container log using PHP-FPM image
I've created [a small repo that uses nginx and PHP-FPM](https://github.com/ericandrewlewis/php-fpm-dockerfile-cant-send-errors-to-container-log) to explain this issue.

I create a PHP-FPM image from Docker hub that specifies a custom [php.ini](https://github.com/ericandrewlewis/php-fpm-dockerfile-cant-send-errors-to-container-log/blob/master/php-fpm/Dockerfile#L2) which [sends errors to `/proc/self/fd/2`](https://github.com/ericandrewlewis/php-fpm-dockerfile-cant-send-errors-to-container-log/blob/master/php-fpm/config/php.ini#L2), which is where I've noticed the [PHP-FPM image sends logs](https://github.com/docker-library/php/blob/master/5.6/fpm/php-fpm.conf#L6). Then I call an [undefined function in `index.php`](https://github.com/ericandrewlewis/php-fpm-dockerfile-cant-send-errors-to-container-log/blob/master/php-fpm/src/index.php#L2), and still only see access logs from both nginx and php-fpm in the container log.

screen shot 2015-10-01 at 2 31 19 pm

### PR DESCRIPTION
**Pull request by ericandrewlewis**
Fixes #140

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

/cc @tianon, @md5

**Comment by yosifkit** [comment]
Thanks for a quick PR!

**Comment by md5** [comment]
LGTM.

It looks like some folks are also setting this:

```
php_admin_value[display_errors] = 'stderr'
```

It might make sense to mention that setting in the docs, though it doesn't seem like a good default to actually add to `php-fpm.conf`.

**Comment by tianon** [comment]
:+1:

**Pull request merged**
