### PR TITLE
Feature/layers optimalization

### PR DESCRIPTION
**Pull request by andreas4all**
Changed templates for generating Dockerfiles. Now we will use less layers and image can be smaller.

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
:+1:

**Comment by andreas4all** [comment]
it's possible to remove PHP5.5 from test? 5.5 is EOL now.

**Comment by luxas** [comment]
Ping @tianon this would be really nice to have :+1:
Also, the travis build flaked a bit

**Comment by yosifkit** [comment]
The current ordering of layers is to maximize docker build cache: especially the `COPY` layers, and the PHP version specific `ENV` layers.  The current order also allows different versions of php to share the same layers for installing dependencies, and setting up the user.  The `apache` versions can share many of their layers as well.  This may not seem important when a user only downloads one version, but this greatly speeds up the build server that has to build 21 unique versions of PHP.

For example, on the Debian based images, if we move the php version or `COPY` above the first `apt-get install` line then that layer, which is ~194 MB, would be part of the new large `RUN` line that would have to be recreated on every PHP version bump or script change and not just when the base image of `debian:jessie` is updated.

**Comment by tianon** [comment]
Closing given @yosifkit's clarification about the current ordering being intentional to maximize build cache (especially sharing build cache as much as possible between versions and variants).

There have been a lot of improvements in the way Docker ships images and layers around to where minimizing the number of layers doesn't make a huge difference in most cases (in my experience), especially when they're empty layers like `ENV` which simply turn into metadata properly rather than being transferred as explicit layers. :+1: :heart:

**Pull request closed without merging**
