### PR TITLE
Tells FPM not to clear the environment in workers

### PR DESCRIPTION
**Pull request by mathroc**
Allows php scripts executed with FPM to access env vars such as env vars
from linked containers

see #74

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM (https://github.com/docker-library/php/issues/74#issuecomment-96827492)

ping @tianon, @md5?

**Comment by md5** [comment]
I followed the discussion in #74 and I agree that it seems reasonable to expose the environment to the `php-fpm` process.

LGTM

**Comment by tianon** [comment]
LGTM

**Comment by AHWEBDEV** [comment]
+1

**Comment by sshilko** [comment]
setting clear_env = no inside pool triggers segfault for me, just fyi

```
PHP 5.6.16-2+deb.sury.org~precise+1 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```

```
Jan 19 19:50:50 packer-virtualbox-iso-1422596416 kernel: [ 1754.342835] show_signal_msg: 12 callbacks suppressed
Jan 19 19:50:50 packer-virtualbox-iso-1422596416 kernel: [ 1754.342844] php5-fpm[6407]: segfault at 1f46a20 ip 00000000006c52f5 sp 00007ffff798a4c0 error 4 in php5-fpm[400000+7d4000]
Jan 19 19:51:20 packer-virtualbox-iso-1422596416 kernel: [ 1784.622389] php5-fpm[6452]: segfault at 490ea20 ip 00000000006c52f5 sp 00007ffff25b55d0 error 4 in php5-fpm[400000+7d4000]
Jan 19 19:51:37 packer-virtualbox-iso-1422596416 kernel: [ 1801.578327] php5-fpm[6494]: segfault at 466ca20 ip 00000000006c52f5 sp 00007fff1f275f80 error 4 in php5-fpm[400000+7d4000]
```

```
Linux packer-virtualbox-iso-1422596416 3.13.0-32-generic #57~precise1-Ubuntu SMP Tue Jul 15 03:51:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tianon** [comment]
@sshilko can you tell us a little bit more about how you've triggered that segfault?  The version number there (`5.6.16-2+deb.sury.org~precise+1`) doesn't look like anything that would/could possibly come from this image, so I'm a little confused and wondering whether there's an easy way for us to reproduce.

**Comment by sshilko** [comment]
this is a [vagrant](https://www.vagrantup.com) box i use:
[puphpet/ubuntu1204-x64](https://atlas.hashicorp.com/puphpet/boxes/ubuntu1204-x64)

It is a Virtualbox guest machine, (v5.0.4) under MacOX 10.11.2 but that probably doesnt matter.

the php is installed 5.6.16 from 
[https://deb.sury.org](https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6)

otherwise there is not much special about it
i just needed to add environment variable to php-fpm from
```
$ cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
PHPENV_ENVIRONMENT=localhost
```
the pool config is

```
[www]
pm = static
pm.start_servers = 5
listen.allowed_clients = 127.0.0.1
pm.min_spare_servers = 5
pm.max_children  = 5
security.limit_extensions  = .php
listen = /var/run/php5-fpm.sock
group = www-data
php_admin_flag[log_errors] = on
listen.owner = www-data
listen.group = www-data
user  = www-data
pm.max_requests  = 100
pm.max_spare_servers = 5
request_terminate_timeout = 300
```
i ended up adding
```
env[PHPENV_ENVIRONMENT] = localhost
```

my php ini is

```
[CUSTOM]
memory_limit=536870912
post_max_size=1M
opcache.validate_timestamps=1
opcache.max_accelerated_files=7963
opcache.interned_strings_buffer=8
realpath_cache_size=64k
log_errors_max_len=99999
max_file_uploads=2
default_charset=UTF-8
error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
mysqli.reconnect=Off
session.cache_expire=300
opcache.memory_consumption=56
zend.detect_unicode=0
opcache.consistency_checks=1
mysqlnd.net_cmd_buffer_size=6144
date.timezone=UTC
expose_php=false
session.auto_start=false
opcache.blacklist_filename=/var/www/localhost/opcache_blacklist
upload_max_filesize=100K
user_ini.cache_ttl=86400
extension=amqp.so
opcache.revalidate_freq=1
mysqli.allow_persistent=true
realpath_cache_ttl=60
mongo.ping_interval=3
error_log=/var/log/php5-fpm-www-error.log
always_populate_raw_post_data=-1
session.use_cookies=false
max_execution_time=600
session.upload_progress.enabled=false
include_path=.
display_errors=false
zend.enable_gc=0
mysqlnd.collect_statistics=0
log_errors=true
```

besides general modules i do have
```
redis
mongo
mongodb
amqp
```

**Comment by yosifkit** [comment]
@sshilko, since you are not using the php in the docker image, I am not sure I see how the release of php from deb.sury.org is related. I would suggest making an issue on https://github.com/oerdnj/deb.sury.org/issues if there is an issue with your configuration or how they build it.

**Comment by NTMan** [comment]
+1 for: clear_env = no by default

**Pull request merged**
