### PR TITLE
Add phpdbg images for php 5.6 and 7.0

### PR DESCRIPTION
**Pull request by Nicofuma**
Since the version 5.6 php provides a powerful debugger built as an alternate SAPI (like fpm or apache).
I think it would be valuable to provide official images for this SAPI.

### CODE REVIEW

**Comment by Baldinof** [comment]
:+1:

**Comment by Nicofuma** [comment]
Up, could it be possible to have some feedbacks please?

**Comment by yosifkit** [comment]
I would like to limit the number of tags to keep it simpler for new users.  Is there any reason we can't just enable `phpdbg` in the `cli` tags?  Would this have bad performance characteristics for those running php scripts with the cli?  Since the `apache` and `fpm` images are not `FROM` the base, it wouldn't effect them.

**Comment by Nicofuma** [comment]
There isn't any reason actually, it's just a separate binary. I've done it like that because it's an SAPI just like fpm and apache. I'll change it later tomorrow.

**Comment by Baldinof** [comment]
Recently I've seen that on `php:7.0-cli` image `phpdbg` is already available in PATH :sparkles:

I'don't know for `5.6-cli` and `fpm/apache` variants.

**Comment by yosifkit** [comment]
Yeah, looks like it is automatically built into the php 7 images. :tada:

Sounds like we just need to add it to php 5.6.  Should we build it in `cli`, `apache`, and `fpm`?

**Comment by Nicofuma** [comment]
Indeed, it looks like it is built by default now (for 7.0): https://github.com/php/php-src/blob/master/sapi/phpdbg/config.m4#L6
But it's not for php 5.6: https://github.com/php/php-src/blob/PHP-5.6.17/sapi/phpdbg/config.m4#L9

**Comment by lakiboy** [comment]
It is still not clear how build a php container with phpdbg support without forking current image. Not sure how to append --enable-phpdbg to PHP_EXTRA_CONFIGURE_ARGS from child container. It could be changed to ONBUILD or ARG to be replaceable from derived images.

**Comment by tyranron** [comment]
@lakiboy quite late, but... (may be it will be useful for somebody)

For PHP7 images you don't need to `--enable-phpdbg`. It's already inside container. Just use it:
```
phpdbg -qrr my_script.php
```

For PHP5 images it can be enabled with some from-source recompilation (Alpine example):
```Dockerfile
RUN apk add --update --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        curl-dev \
        libedit-dev \
        libxml2-dev \
        openssl-dev \
        sqlite-dev \
 && docker-php-source extract \

 && cd /usr/src/php \
 && ./configure --enable-phpdbg \
 && make -j "$(getconf _NPROCESSORS_ONLN)" \
 && make install-phpdbg \

 && docker-php-source delete \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/*
```
Then use it.

Note that:
* PHP7 images contain `v0.5.0` version of `phpdbg` and PHP5 images contain `v0.4.0` version.
* for PHP5 `phpdbg` [does not support](https://github.com/krakjoe/phpdbg/issues/150) functions to measure code coverage

**Comment by tianon** [comment]
Given that PHP 7 includes `phpdbg` already by default, and that upstream recommends users make the leap (5.5 was EOL on 10 Jul 2016, 5.6 is EOL on 31 Dec 2018), I'm going to close this (finally :disappointed:).  Thanks for the discussion! :+1: :heart:

**Pull request closed without merging**
