### PR TITLE
Upgrade to PHP 7 GA.

### PR DESCRIPTION
**Pull request by skyred**
PHP 7 has arrived: https://github.com/php/php-src/releases/tag/php-7.0.0

Also, switching the "latest" tag to 7

### CODE REVIEW

**Comment by yosifkit** [comment]
Aw, Travis fails to build :cry:.  Looks like we need to resync the `7.0` file to be more like the rest. In other words, it needs to change where it is downloading from and gpg verify it :tada:.  Want to make the updates?

Also, looks like it won't be signed on php.net until tomorrow ("release will be brought out on December 3rd" [php.net](https://secure.php.net/archive/2015.php#id2015-11-26-1))

**Comment by skyred** [comment]
it's already Dec.3rd in Shanghai :smile: I will re-trigger the build once php.net has published the announcement and see if we can pass the build.

**Comment by tianon** [comment]
Looks like downloads are available and the GPG key is listed on
https://secure.php.net/gpg-keys.php so if we just switch from ~ab's
personal upload space back to the normal download methods, we should be
golden and ready for the official announcement.

**Comment by thaJeztah** [comment]
Nice! Thank you!

ping @tianon @yosifkit PTAL

**Comment by andrerom** [comment]
+1 :tada:

**Comment by yosifkit** [comment]
LGTM!

**Comment by RobLoach** [comment]
@skyred :+1:

**Pull request merged**
