### PR TITLE
add zts support

### PR DESCRIPTION
**Pull request by mikk150**
Added zts support so who wants can use pthreads
I haven't made zts support for fpm or apache available, because obviously if using pthreads, one does some kind of worker and workers are run at console anyway

### CODE REVIEW

**Comment by tianon** [comment]
Ah interesting, and you've done this in a way that `update.sh` is happy! :heart:

This sounds sane to me.

**Comment by tianon** [comment]
LGTM

cc @yosifkit

**Comment by mikk150** [comment]
So how is it?, can i start using docker official images yet? @yosifkit

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
