### PR TITLE
Upgrade alpine to v3.5

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by tianon** [comment]
I'm +1 on the change, but only after the Alpine image maintainers update `latest` to point to `3.5` (see https://github.com/docker-library/official-images/pull/2489#discussion_r93885746).

**Comment by PeterDaveHello** [comment]
@tianon now the `alpine:latest` is same as `alpine:3.5` :)

**Comment by yosifkit** [comment]
Similar error to https://github.com/docker-library/httpd/pull/41
```console
+ apk add --no-cache --virtual .build-deps autoconf file g++ gcc libc-dev make pkgconf re2c curl-dev libedit-dev libxml2-dev openssl-dev sqlite-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libressl-dev-2.4.4-r0:
    conflicts:
               openssl-dev-1.0.2j-r2[pc:libcrypto=2.4.4]
               openssl-dev-1.0.2j-r2[pc:libssl=2.4.4]
               openssl-dev-1.0.2j-r2[pc:openssl=2.4.4]
    satisfies: libssh2-dev-1.7.0-r2[libressl-dev]
               libssh2-dev-1.7.0-r2[pc:libcrypto]
               libssh2-dev-1.7.0-r2[pc:libssl]
               curl-dev-7.52.1-r0[libressl-dev]
  openssl-dev-1.0.2j-r2:
    conflicts:
               libressl-dev-2.4.4-r0[pc:libcrypto=1.0.2j]
               libressl-dev-2.4.4-r0[pc:libssl=1.0.2j]
               libressl-dev-2.4.4-r0[pc:openssl=1.0.2j]
    satisfies: libssh2-dev-1.7.0-r2[pc:libcrypto]
               libssh2-dev-1.7.0-r2[pc:libssl]
  .build-deps-0:
    masked in: cache
    satisfies: world[.build-deps]
```

**Comment by tianon** [comment]
I successfully build-tested `7.1/alpine`, `7.0/alpine`, and `5.6/alpine` -- hopefully Travis shows us that the rest are OK too. :see_no_evil:

**Comment by PeterDaveHello** [comment]
@tianon looks great! I forget to check its dependencies, sorry for that!

**Comment by tianon** [comment]
Revert incoming in https://github.com/docker-library/php/pull/360 -- see https://github.com/docker-library/golang/pull/131#issuecomment-270677556 for more details.

**Comment by im-kulikov** [comment]
@tianon @PeterDaveHello i'll try to build php7.1 with alpine3.5 and it works. See [repo](https://github.com/ulabs-org/php7-base)

Yep, in alpine 3.5 are:

> Switch from OpenSSL to LibreSSL

they are notice about that on [release note page](https://alpinelinux.org/posts/Alpine-3.5.0-released.html)

Now there is no difference between build with openssl or libressl, all sources placed in `/usr/include/openssl/`.

**Pull request merged**
