### PR TITLE
added touch to create ini files if not existing

### PR DESCRIPTION
**Pull request by ildanno**
Added a `touch $file` before every append because it fails if file does not exists

### CODE REVIEW

**Comment by yosifkit** [comment]
I don't see this solving any problem. The redirect will create the file if it does not exist (http://www.tldp.org/LDP/abs/html/io-redirection.html), which it does happily.  I ran `docker-php-ext-install pdo pdo_mysql` in `php:5.6-fpm` and was able to see that pdo_mysql was enabled in `php -i` and I was able to create a new PDO connecting to a mysql host.

**Comment by ghvaldez** [comment]
I'm using php-5.6-apache and adding the docker-php-ext-install pdo pdo_mysql I get the following error at build time.

+ cd /usr/src/php/ext/pdo
+ phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
+ ./configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... no
configure: error: in `/usr/src/php/ext/pdo':
configure: error: C compiler cannot create executables
See `config.log' for more details

If it works in fpm then whatever was fixed there needs to be added to apache version

**Comment by md5** [comment]
@ghvaldez that should have been fixed in #73. You might want to do a `docker pull php:5.6-apache` to confirm you have the latest updates to the image.

**Comment by ghvaldez** [comment]
@md5 That was it.  Thanks!

**Comment by ildanno** [comment]
I've got this problem with docker 1.4 running on boot2docker, but i'm not able to reproduce this anymore. Closing.

**Pull request closed without merging**
