### PR TITLE
Explicitly enable "mbstring" by default (since certain pecl bits cannot work properly otherwise)

### LINKED ISSUE #34: it should enable `--enable-mbstring` during compilation

### LINKED ISSUE #195: pecl/pear requires mbstring
I installed mbstring in docker `docker-php-ext-install mbstring` and then trying to install mailparse `pecl install mailparse-2.1.6`. pecl result in `pecl/mailparse requires PHP extension "mbstring"`. After grep mbstring from php -i, it does display mbstring result. Anyone know how to enable pecl or pear to load mbstring?

Thanks

### PR DESCRIPTION
**Pull request by tianon**
Fixes #34
Fixes #195

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by bizmate** [comment]
@tianon thanks for changing this, i tried 6 hours ago to install mbstring and it looks like it was working https://hub.docker.com/r/diegogullo/php_docker_56/ -> https://github.com/bizmate/php_docker_56/blob/master/Dockerfile#L14

Maybe after all it is not needed by default? I can see it enabled in this image and it works fine. Initially in the debian box i could not see a way to install it but using the line above it looks alright

**Comment by yosifkit** [comment]
Yeah, it could be installed after, but as far as I know `pecl` can't use it unless it is built in to php (https://github.com/docker-library/php/issues/195#issuecomment-189386616)

**Comment by bizmate** [comment]
Thanks for point that out explicitly, i totally skipped that part. Still I dont see the images being updated on docker hub. Arent they auto-built?

**Comment by yosifkit** [comment]
We don't use hub autobuilds. Our process goes through https://github.com/docker-library/official-images for repeatable builds that utilize docker build caching.  @tianon is working on the PR to update a bunch of them, but the images probably won't show up until tomorrow morning.

**Pull request merged**
