### PR TITLE
Extensions Dependencies autoinstall

### PR DESCRIPTION
**Pull request by Iazel**
As of issue #265, I have enhanced the `docker-php-ext-install` to automatically install dependencies needed by any given extensions. I've also refactored the said script for a better readability.
# How it works

Because each OS uses a different Packet Manager, the script rely on `<OS>-only/docker-php-ext-install-helper.sh`; it expose 3 functions: `hook_prepare`, `hook_clean` and `install_libs`.
This file will be merged with `docker-php-ext-install` through `update.sh`.

The script fetch the dependencies to install for the given extension from `/usr/src/php-ext-deps.tsv`, a tab separated value file that is OS-unique too. For extension with more than one deps, you simply repeat it:

``` tsv
gd  libfreetype6-dev
gd  libjpeg-dev
gd  libpng12-dev
```
# Note

Please note that I changed https://github.com/Iazel/php/blob/extdeps/update.sh#L16 to include the exact supported versions. I think this way is cleaner.
# Still to do

A list of dependencies for `alpine` and probably a better helper script. I don't know much about this OS yet, any contribution will be appreciated :+1: 
I'm also not sure if I included all the required libs for all the available exts.

---

I hope this will be useful to everyone :)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Wow! Great idea!

**Comment by Iazel** [comment]
Hi,
I fixed and increased the support for alpine and also rebased the PR against the current master

**Comment by Iazel** [comment]
Uhm, I cannot understand why this fails. I tried in my machine and docker-php-ext-install works as expected, but I haven't tried all of them. If anyone can point me on the test suite would be great!

**Comment by Hipska** [comment]
Hi, I noticed that you can install zip php extension with `zlib1g-dev` instead of `libzip-dev`

**Comment by tianon** [comment]
Closing, given the rationale in https://github.com/docker-library/php/issues/75#issuecomment-353673374. :heart:

**Pull request closed without merging**
