### PR TITLE
Add alpine3.8 for php 7.2

### PR DESCRIPTION
**Pull request by nick-zh**
Hey guys, i dont know if this is enough, i compared 3.6 and 3.7 and found that only the base image was needed to change, so i hope this will do for 3.8 as well (#683).

### CODE REVIEW

**Comment by nick-zh** [comment]
@tianon @yosifkit please let me know if there is something missing guys

**Comment by TimWolla** [comment]
for reference, see this comment in #677: https://github.com/docker-library/php/pull/677#discussion_r201484351

**Comment by nick-zh** [comment]
@TimWolla thank you, i added this as well

**Comment by TimWolla** [comment]
@nick-zh My comment was primarily intended for the maintainers (tianon / yosifkit): Ideally #677 should be merged first, because you forgot to update `update.sh` to add Alpine 3.8 support: https://github.com/docker-library/php/blob/b9d625cb6a5933d457f9304bc6b07122844bc777/update.sh#L128

**Comment by lbadger** [comment]
Will this have support for Argon 2?

**Comment by jesuGMZ** [comment]
Are there something blocking this merge? Would like to not change my current multi-stage Dockerfile based on Alpine to Debian only for Argon2 :)

**Comment by teohhanhui** [comment]
Be careful!

PHP 7.2's `password_verify` does **NOT** support `argon2id`. If you have previously been using the `sodium` extension's `sodium_crypto_pwhash` to encode the password, the default algorithm has been `argon2id` for some time now. Just a heads-up!

Reference: https://igotaprinter.com/blog/argon2i-php-password-hash-not-compatible-libsodium.html (site has expired SSL certificate :laughing:)

**Pull request merged**
