### PR TITLE
Return backwards compatibility to the way we handle /usr/src/php/ext/* (especially for user-supplied subdirectories looking to utilize docker-php-ext-* for non-core modules)

### LINKED ISSUE #266: Avoiding breaking changes such as PR #256
Hi,

PR #256 changed the way how it finds the installable packages, and then now I am no longer able to install third party packages such as PHPRedis using only `docker-php-ext-install` and have to rewrite all the existing Dockerfiles.

I've found some solution at https://github.com/docker-library/php/issues/262#issuecomment-233108680 which wraps the extension installation process with `docker-php-source extract` and `docker-php-source delete`, then adds the extension name to `/usr/src/php-available-exts` to "whitelist" the additional extension name. Obviously this solution "works as intended", however, as you can see it requires all the developers to rewrite their customized php Dockerfiles.

The question is, why was this big breaking change applied to all the existing php Dockerfiles?
Was there no option to create "a brand new version with breaking changes" and leave the existing Dockerfiles untouched?
I have been using this php docker container for months on some enterprise-class solution, so I would like to avoid this kind of breaking changes to be happening as much as possible.

There is still last-resort solution which "copies the Dockerfile itself and customize the copied one," however I think it's not how this kind of publicly-used Dockerfile should be :(

I would very much appreciated if you could consider not to make such a breaking change to all the existing Dockerfiles within the same version. Thanks!

### PR DESCRIPTION
**Pull request by tianon**
Closes #269
Closes #268
Closes #266

### CODE REVIEW

**Comment by tianon** [comment]
The gist of how this works is:

1. if `/usr/src/php` already exists when we start, we do not remove it (allows for dropping folders in `/usr/src/php/ext/*` as before)
2. if we create `/usr/src/php` ourselves via `extract`, we `delete` it
3. no more cache for existing extensions -- extracting is reasonably fast, and has to happen for actual build anyhow, so just do it sooner

**Comment by shouze** [comment]
LGTM

**Comment by yosifkit** [comment]
LGTM

**Comment by partounian** [comment]
Sorry but I'm a bit new to this, and these past few issues have me confused. If I need PECL to install modules would I just use docker-php-ext-* now?

**Comment by tianon** [comment]
No, `pecl` is absolutely still appropriate to use directly -- the only `docker-php-ext-*` script which should be used when installing from `pecl` is `docker-php-ext-enable` (if needed).

This PR simply adds back semi-support for the strange way folks were dumping extension sources into subdirectories of `/usr/src/php/ext` and using `docker-php-ext-*` to build/install them.

**Comment by partounian** [comment]
Oh okay, well previously I was getting an issue for phpize previously, and couldn't figure out how to instal the Alpine dev package for that to fix the issue. Any pointers?

**Comment by yosifkit** [comment]
@partounian, are you asking about figuring out which `-dev` is needed to install a specific php plugin (https://pkgs.alpinelinux.org/contents to find which package has the header file needed) or about installing general development tools for phpizing a plugin (`RUN apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS  && phpize ... && apk del .phpize-deps`)?

**Comment by partounian** [comment]
Well I just need to install the plugins for APCu, and Graphicsmagick for PHP5.5. So my question is, what's the best way to get those installed? For gmagick I am already downloading the pkg with apk testing, but can't get the plugin installed with PECL.

**Pull request merged**
