### PR TITLE
Add PHP 8.3 RC

### PR DESCRIPTION
**Pull request by jnoordsij**
Note the second commit should be the result of the bot when the QA releases page is updated, but I manually added it to test image builds a little ahead.

Note: this means it probably is a good thing to wait for the release to appear there before merging.

### CODE REVIEW

**Comment by yosifkit** [comment]
Thanks for the PR!

Ah, the verify templating is failing because the execute permission was lost:

```console
$ ./apply-templates.sh
...
$ git diff
diff --git a/8.3-rc/bullseye/apache/apache2-foreground b/8.3-rc/bullseye/apache/apache2-foreground
old mode 100644
new mode 100755
diff --git a/8.3-rc/buster/apache/apache2-foreground b/8.3-rc/buster/apache/apache2-foreground
old mode 100644
new mode 100755
```

**Comment by tianon** [comment]
> Note: this means it probably is a good thing to wait for the release to appear there before merging.

Makes sense; I guess we'll keep an eye on https://github.com/php/web-qa/commits/master :sweat_smile:

**Review by yosifkit — APPROVED** [review]
🎉 https://github.com/php/web-qa/commit/6fbbe69043962a26f50996a55d806d6d1e0542d7

**Comment by jnoordsij** [comment]
Looks all set! Will be a race to the bot updating `8.2-rc` in the `master` branch and causing a merge conflict? 😅

**Pull request merged**
