### PR TITLE
Add a docker-php-composer-install script

### PR DESCRIPTION
**Pull request by mathroc**
As discussed in #177 composer is not the official php dependency manager but it's the de facto standard 

This PR proposes to make it really easy to install composer ["the right way"](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md)

This also makes it possible to install different version (stable, preview, snapshot) of composer

> ⚡ docker run --rm php:7-alpine docker-php-composer-install --help
> Composer Installer
> ---
> 
> Options
> --help               this help
> --check              for checking environment only
> --force              forces the installation
> --ansi               force ANSI color output
> --no-ansi            disable ANSI color output
> --quiet              do not output unimportant messages
> --install-dir="..."  accepts a target installation directory
> --preview            install the latest version from the preview (alpha/beta/rc) channel instead of stable
> --snapshot           install the latest version from the snapshot (dev builds) channel instead of stable
> --version="..."      accepts a specific version to install instead of the latest
> --filename="..."     accepts a target filename (default: composer.phar)
> --disable-tls        disable SSL/TLS security for file downloads
> --cafile="..."       accepts a path to a Certificate Authority (CA) certificate file for SSL/TLS verification

Dockerfile usage exemple:

```
FROM php:7-alpine

RUN docker-php-composer-install && composer global require phpunit/phpunit
```

todo:
- [x] add `docker-php-composer-install` script
- [x] add script to images
- [x] [documentation](https://github.com/docker-library/docs/pull/640)
- [x] set env var "COMPOSER_ALLOW_SUPERUSER" to remove warning about running composer as root
- [x] add `/root/.composer/vendor/bin/` to `$PATH`
- [x] run update.sh

Do you think this can be a good solution ?

### CODE REVIEW

**Comment by mathroc** [comment]
should I install the latest version of composer by default ? (https://github.com/docker-library/php/issues/177#issuecomment-233490858)

**Comment by mathroc** [comment]
I've updated the PR to resolves pending conflicts. is there anything I can do to help making a decision about including composer or not in this image ?

**Comment by yosifkit** [comment]
I am not sure we had concluded that composer should be included in the PHP images and I don't see much of a difference between installing it and installing a script to install it.  In either case we are sanctioning composer and inviting issues in dealing with "using composer in docker".  Perhaps we just need to add this script as an example to the [docs](https://github.com/docker-library/docs/blob/2d6e8ef980ee4f393148117f1295f7e3d90ae442/php/content.md)?

**Comment by mathroc** [comment]
yeah, I know that's nothing is set in stone yet. If adding it into the image is not an option, yeah, maybe adding that to the doc is better than nothing. 
but honestly, it would be a pita to go to the doc each time I want to install docker inside a php image. plus, this PR also add an env var & update $PATH. 

the difference between adding `RUN docker-php-composer-install` and copying and pasting the whole script + adding the env var and modifying $PATH is quite big

also, improvements to the script would need to be discovered manually and wouldn't come with a `docker pull php`

**Comment by alcohol** [comment]
Could be a nice addition. I started on https://github.com/composer/docker but kind of lost track/motivation. Composer is just so easy to install/pull in, not sure it needs a container by itself. Also lots of discussion on whether or not it should come with a gazillion php extensions and what not. As part of the PHP base image, a lot of that discussion would be void since most users want to extend the php base image for their own app anyway.

Just wondering; wouldn't it make sense to add the composer home directory inside the container and specify it through the environment as well (e.g. `COMPOSER_HOME=/composer`) and then exposing this as a named volume?

**Pull request closed without merging**
