### PR TITLE
Upgrade to RC1 Release

### PR DESCRIPTION
**Pull request by skyred**
http://php.net/archive/2015.php#id2015-08-21-1

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @skyred, looks like you missed one though; https://github.com/docker-library/php/blob/master/7.0/Dockerfile

When fixing that, could you also squash your commits, so that's there a single commit in this PR?

**Comment by skyred** [comment]
@thaJeztah Thank you and done.

**Comment by thaJeztah** [comment]
Thanks! Although I'm not a maintainer in this repository, I think the maintainers here like to have the commits squashed (i.e., combine the three commits to a single one). If you don't know how that works, you can find some instructions in the contribution guide of the Docker documentation; https://docs.docker.com/project/create-pr/#rebase-your-branch. Those instructions apply to the "Docker" project, but the same methods should work here as well.

Hope it helps :+1:

**Comment by skyred** [comment]
@thaJeztah Thanks for pointing me to the right direction. done.

**Comment by thaJeztah** [comment]
@skyred excellent, thanks so much! LGTM

ping @tianon @yosifkit for review and merge :+1:

**Comment by tianon** [comment]
LGTM :heart:

**Pull request merged**
