### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by rsumilang**
Fixing apache package.

### CODE REVIEW

**Comment by tianon** [comment]
I think we need a bit more context as to why we should prefer `apache2.2-bin` over `apache2-bin`, especially when [the description for the `apache2.2-bin` package in `jessie`](https://packages.debian.org/jessie/apache2.2-bin) says "`This is a transitional package for apache2-bin, and can be safely removed after the installation is complete.`".

**Comment by rsumilang** [comment]
Sorry about that :) The reason I changed it to the `apache2.2-bin` over the `apache2-bin` is because the `apache2-bin` isn't found in the `apt-get` anymore which causes the Dockerfile to fail when building. I'm open to another solution. Thanks!

**Comment by yosifkit** [comment]
I'm not sure how `apache2-bin` wouldn't exist in your apt anymore, it is a dependency of `apache2.2-bin`.  Maybe you had a bad `apt-get update`?

**Comment by Lewiscowles1986** [comment]
> I think we need a bit more context as to why we should prefer apache2.2-bin over apache2-bin, 

Actually we should be pushing 2.4.17 as the latest stable version of Apache 2

**Comment by 1354092549** [comment]
I don't think it should be.
I use some of the new features of Apache2.4
*(my english is not very good, but i am working on it)*

**Comment by yosifkit** [comment]
Yeah I think we should stick with `apache2-bin` since that pulls in [`2.4.10` in Debian jessie](https://packages.debian.org/jessie/apache2).

**Pull request closed without merging**
