### PR TITLE
Add PHP 8.3.0

### PR DESCRIPTION
**Pull request by jnoordsij**
Modelled after #1353.

Given the [8.3.0 tag is here](https://github.com/php/php-src/releases/tag/php-8.3.0), the release will follow soon.
This is awaiting the official release to be available on https://www.php.net/releases/index.php?json&max=1&version=8.3, hence the draft state.

Running `mkdir 8.3 && ./update.sh` and commiting the result should suffice if anyone comes by this when the release is available and I haven't managed yet to update this ;)

### CODE REVIEW

**Comment by WyriHaximus** [comment]
@jnoordsij It has just been released: https://www.php.net/archive/2023.php#2023-11-23-2

**Comment by parallels999** [comment]
Ready 👍👍

**Comment by jnoordsij** [comment]
Updated to include the new templates!

Note: I have deliberately updated on a commit-by-commit basis, so that if the bot comes by to update the other tags before this gets merged, hopefully git is able to deduce what's happening by spotting duplicate commits and will still be willing to merge this.

**Comment by angeljqv** [comment]
Bot not working?

**Comment by LaurentGoderre** [comment]
@angeljqv the bot updates supported version so this is needed to add 8.3 to the list of supported version.

**Review by LaurentGoderre — APPROVED** [review]

**Comment by damien-louis** [comment]
It's time to merge @jnoordsij?

**Comment by Yurunsoft** [comment]
Looking forward to it!

**Comment by xgbnl** [comment]
什么时候能拉取8.3的镜像，我的laravel扩展包正准备升级

**Comment by ToshY** [comment]
@LaurentGoderre @yosifkit @tianon Could a maintainer spare some to merge this? Seems people are eagerly waiting for it 🙂

**Comment by cedric-anne** [comment]
Or people could simply wait a bit and be patient. I guess none of them have an application specifically designed for PHP 8.3 to push in production inside a docker container just a few days after the PHP 8.3 release date.

Maintainer could spare some time away from their computers, for instance to spend time with their families and/or friends, or to just enjoy some free time.

**Comment by jnoordsij** [comment]
> It's time to merge @jnoordsij? ;-p

That'll require a maintainer of the official images. Given that it was Thanksgiving last week, I assume they have a well-deserved long weekend and will be here later today to merge this. After that there will be a few more steps + waiting on the build (see also https://github.com/docker-library/php#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet), so just sit back for a bit and the image will appear at some point.

For those eager to test things: there's always the option to run all your tests on the already available `8.3-rc` version, which should behave practically equivalent for almost all purposes, and is probably a good thing to do earlier on if your workflow allows you to test this in preparation for the final release (and as an opportunity to provide feedback before the stable release!).

Finally you can always just take any of the Dockerfiles from this repository or any PR and build them for yourselves if you're not willing to wait for the actual image to show up.

**Comment by patrickomeara** [comment]
A huge thanks to all maintainers. 🙏🏻

**Comment by fibis** [comment]
Also not working for me

**Comment by yosifkit** [comment]
https://github.com/docker-library/official-images/pull/15776#issuecomment-1828743274

Short answer: they are still building; only some architectures have finished.

**Comment by sbuerk** [comment]
> Thanks for merging this.
> 
> Is it expected to work on an amd64 box?
> 
> ```
> #2 [linux/amd64 internal] load metadata for docker.io/library/php:8.3-apache
> #2 ERROR: no match for platform in manifest: not found
> ```
> 
> Or is this just down to me being too eager to `docker pull` it?

jesus ... the pipeline army is running and building all variants for 6 platforms ! That take some time after merge in the official repo.

Get a nap of 2 or 3 hour and look again, they maight be there then.

Good job to the maitainers. TBH I also waiting for the images but just checkif if my tags and  platforms are there before building own image based on them. No need to make the birds fly away .. because you cannot wait.

Are that the first images you are waiting for ? Use https://hub.docker.com/_/php/tags anter the image variant/tag you want and check if the platform you need is build for it:

Current for me waiting:
Auswahl_1458

old RC6

Auswahl_1459

Are you building your images for all os/arch like the official php images ? 

We should be patient. Personally I find that the image are coming in now is more than sufficient. Would it be nice to had them before the weekend ? Sure, If it would have been important it's still possible to build the "FULL" image with your additions based on that repository if you can't wait a couple of days.

Again -- great work and a good backbone to maintainer of these images. Everyone earns time off from open source projects and work.

**Comment by lol768** [comment]
Thank you for pointing out where the arch is shown in the UI, that's useful. Fully appreciate colleagues across the pond have had their holidays recently (given the import of Black Friday sales over here, you can't forget).

For anyone else, curious I think the Jenkins job is here: https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/lastBuild/changes

**Comment by damien-louis** [comment]
Thanks a lot to everybody who work on this PR

**Pull request merged**
