### PR TITLE
Use already available curl and consistent code style

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by yosifkit** [comment]
I'm half tempted to just remove `curl` (and keep the add/remove of `wget` since it cleans up better than curl in Debian) since I can't see a good reason why it was kept installed.  It was first kept installed in https://github.com/docker-library/php/pull/9 and was questioned when added initially to alpine in https://github.com/docker-library/php/pull/202#commitcomment-16782605.

Does php itself (or pecl/pear) use `curl` directly or is it only via libcurl?

Though [we](https://github.com/docker-library/wordpress/blob/a0c880d2a238c0703025aa136516bb06279c6c02/Dockerfile-debian.template#L71) probably wouldn't be the only dependent image that assumes `curl` exists. :cry:

**Comment by tianon** [comment]
I agree, including `curl` in the image itself instead of just `libcurl` to
satisfy PHP's `curl` plugin seems odd and I wish we had more history to see
why we added it in the first place.

**Comment by J0WI** [comment]
curl is also used in tests:
https://github.com/docker-library/official-images/blob/4e2b0889b438fad2b0ad5fc3d2f2f018d544afcc/test/tests/wordpress-apache-run/run.sh#L6-L7

For Alpine most `wget` use cases are already covered by BusyBox.

**Comment by J0WI** [comment]
> it cleans up better than curl in Debian

Maybe this has been enhanced?
`apt install --no-install-recommends curl` installs 26 packages on `debian:stretch-slim` and only 16 in `debian:buster-slim`. `apt purge --autoremove curl` removes them correctly.

**Comment by J0WI** [comment]
The transition to Alpine 3.10 (#845)/Debian Buster might be a good chance to remove `curl` in favor of `libcurl`.

**Comment by tianon** [comment]
That's a good idea -- perhaps we should also do so for 7.4-rc+, although I think this is enough change for one PR (I added a few extra bits and did a rebase). :+1:

**Pull request merged**
