### PR TITLE
Allow to install extension without enabling it

### PR DESCRIPTION
**Pull request by bilhackmac**
This little change allow to install extension without enabling it.

It can be useful for preparing base images and speedup sub build in CI context

### CODE REVIEW

**Comment by JoelLinn** [comment]
If I want to enable the extension later on calling `docker-php-ext-enable my-extension` would be enough?

**Comment by bilhackmac** [comment]
In principle yes… but i'm going a bit fast and i tested with an extension already activated.

I pass the MR in WIP and I correct as soon as I have time

**Comment by bilhackmac** [comment]
After doing some more relevant tests I can confirm I did it right.

For exemple test with `bcmath`
```shell
php -m | fgrep bcmath
# <no result>
docker-php-ext-install --no-enable bcmath
# <install output>
php -m | fgrep bcmath
# <no result>
docker-php-ext-enable bcmath
php -m | fgrep bcmath
# bcmath
```

Another with `pdo_mysql`
```shell
php -m | fgrep pdo_mysql
# <no result>
docker-php-ext-install --no-enable pdo_mysql
# <install output>
php -m | fgrep pdo_mysql
# <no result>
docker-php-ext-enable pdo_mysql
php -m | fgrep pdo_mysql
# pdo_mysql
```

**Comment by yosifkit** [comment]
> It can be useful for preparing base images and speedup sub build in CI context

If this is to create custom base images in a CI pipeline to speed up diverse child images, why can't the php modules just be left enabled for all of them?

**Comment by bilhackmac** [comment]
All child images do not need all extensions, it is a will on the project to activate only the strict necessary… I know it's not the docker way to install unnecessary resources but it will really speed up my CI

```
PHP official image
  ├ Install ext A
  ├ Install ext B
  ├ Install ext C
  ├ Install ext D
  └ Copy custom global config
    │ # Child image 1
    ├ Enable ext A
    ├ Enable ext C
    ├ Copy custom image config
    │ # Child image 2
    ├ Enable ext A
    ├ Enable ext B
    ├ Copy custom image config
    │ # Child image 3
    ├ Enable ext B
    ├ Enable ext D
    │ # Child image 4
    ├ Enable ext B
    ├ Enable ext D
    ├ Install and enable ext Z that is the only child image that need it
    │ # Child image X
    ├ Enable ext C
    ├ Copy custom image config
    ┆
```

Deps are installed only once, extensions are builds only once too.

We can have up to 51 child images… and growing

**Comment by yosifkit** [comment]
I would have said to just pass `--ini-name=/dev/null`, but that is only an argument to `enable` and doesn't handle absolute paths (we'll look to fix those bits).

Why not just `rm $PHP_INI_DIR/conf.d/*pdo_mysql*` after install?

**Comment by bilhackmac** [comment]
Yes I can `rm $PHP_INI_DIR/conf.d/*` after installing all needed modules, indeed.

I'll just find it's a more convenient way with `--no-enable`.

So, as you wish, i adapt

**Comment by yosifkit** [comment]
Added https://github.com/docker-library/php/pull/1021 so that `docker-php-ext-install --ini-name=/dev/null` will work.

**Comment by bilhackmac** [comment]
Thx

**Comment by mlaokvee** [comment]
?

**Pull request closed without merging**
