### PR TITLE
Add docker-php-ext-disable

### LINKED ISSUE #220: Include a docker-php-ext-disable
I saw that there is no disable script here - ideally, it'd be great to replicate both `php5enmod` and `php5dismod` functionality.

I created a disable script based on `docker-php-ext-enable` and am copying it in my build.  The script just looks for the existence of the extension ini file and removes it - but not sure if there is a more ideal way to handle this?  Willing to PR it, if there's any interest.

The use case for me was to be able to enable or disable xdebug on the fly when running PHPUnit:

`docker exec -ti php sh -c "docker-php-ext-disable xdebug && vendor/bin/phpunit`

### PR DESCRIPTION
**Pull request by pproenca**
Introduce a script to disable extensions

this closes #220

### CODE REVIEW

**Comment by pavlunya** [comment]
There is a small issue with this script
After multiple usage of docker-php-ext-enable/docker-php-ext-disable
I have a lot of newlines between xdebug config and zend_extension instruction
So it looks like this after a while
```ini
xdebug.remote_enable=1
xdebug.remote_autostart=0
xdebug.remote_port=9001
xdebug.remote_host=172.30.18.154
xdebug.idekey="PHPSTORM"







zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so
```
A lot of useless newlines :(
I think this behaviour should be fixed

**Comment by tianon** [comment]
Sorry for the super-long review delay :disappointed:

Given https://github.com/docker-library/php/pull/178 (the addition of `--ini-name` to `docker-php-ext-enable`), and the determinism of the filenames `docker-php-ext-enable` already generates, I'm not sure I understand what this offers above simply using `rm ...` on the exact `*.ini` path, especially if a custom `--ini-name` was used to make sure that it's exactly what was expected?  That will make sure any additional configuration is removed as well, and leaves the "magic" in the control of the user (rather than a script trying to guess what they intended).

**Comment by tianon** [comment]
Closing with the same rationale as https://github.com/docker-library/php/issues/220#issuecomment-353677238:

> Given that https://github.com/docker-library/php/pull/178 added `--ini-name` for explicitly controlling the exact filename `docker-php-ext-enable` creates (and that the filenames it uses are already trivially deterministic), I'm going to close this with the recommendation that users who need to disable extensions after previously enabling them simply use `rm` on the appropriate file (or `sed`, if they've added additional configuration to the file since enabling the extension).  Thanks!

**Comment by silentwarrior** [comment]
It adds consistency. When you have a button that enables something, there should be a button that disables that something.

What I dont understand is the need to jump through hoops to disable something you easily enabled before.

For example, I use Docker for local development, I go in and enable Xdebug with a simple command, then I should be able to disable it quickly.

Having this scripts only adds value, retracts nothing and its already done.

**Comment by tianon** [comment]
Ok, let me put this another way.

Enabling an extension is trivial -- the most that will happen if one is enabled twice is a warning, and thus it can be enabled in any configuration file.

Disabling is not so trivial.  The given extension could be enabled in any of a number of configuration files, and could even be enabled more than once.  Additionally, it could also be a built-in extension (which are somewhere between hard and impossible to disable).

For the Docker use case specifically, extensions will typically be enabled in the `Dockerfile` and thus not ever disabled (or enabled at runtime and then disabled by destroying that container and re-creating a new one from the pristine original state).

**Comment by roma-glushko** [comment]
@tianon so what's officialy right way to disable xdebug using this build?

**Comment by yosifkit** [comment]
@roma-glushko, I would say the simplest way is to build your image so that it doesn't contain unwanted extra modules enabled (aside from the built-in modules).

But if you are trying to deploy your "dev/QA/test" image directly to production while disabling testing modules, then you just need to rm the `.ini` file that enables it. If you used the `docker-php-ext-enable` or `docker-php-ext-install` scripts provided, the filename would be determined by this line in the script:

https://github.com/docker-library/php/blob/d6b950cc18b2977a96f472345024bed00cd07814/docker-php-ext-enable#L106

If you used your own `php.ini` file to enable specific modules, then you would just overwrite that with a new custom file that no longer enables those modules.

**Comment by laukstein** [comment]
There are php extensions like php, sqlite3, etc. that it wouldn't disable with `docker-php-ext-disable`.
Can't figure out how to disable by using `php:fpm-alpine`. Open https://github.com/docker-library/php/issues/995 for it.

**Comment by laukstein** [comment]
I recommend to reconsider adding `docker-php-ext-disable`

It will need to use this lines https://github.com/docker-library/php/blob/a7e2de0e8f2b902bc36be6f5d61c0b4fcd1052ff/docker-php-ext-enable#L69-L93
to avoid error `docker-php-ext-disable: line 61: nm: not found`.

**Pull request closed without merging**
