### PR TITLE
Setup the `$APACHE_RUN_DIR` and `$APACHE_LOCK_DIR` directories in runtime

### LINKED ISSUE #250: Cannot boot `php:*-apache` with `--tmpfs /run`
I tried tmpfs with the `php:5-apache` and `php:7-apache` images, neither are working.

``` bash
$ docker run --tmpfs /run php:5-apache
AH00526: Syntax error on line 3 of /etc/apache2/apache2.conf:
Invalid Mutex directory in argument file:/var/lock/apache2
```

``` bash
$ docker run --tmpfs /run php:7-apache                                                                         
AH00526: Syntax error on line 3 of /etc/apache2/apache2.conf:
Invalid Mutex directory in argument file:/var/lock/apache2
```

I tried the `httpd:latest` image, it's ok with `tmpfs`:

``` bash
$ docker run --tmpfs /run httpd:latest                                                                         
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
[Mon Jul 04 04:51:01.359769 2016] [mpm_event:notice] [pid 1:tid 140197155190656] AH00489: Apache/2.4.20 (Unix) configured -- resuming normal operations
[Mon Jul 04 04:51:01.360029 2016] [core:notice] [pid 1:tid 140197155190656] AH00094: Command line: 'httpd -D FOREGROUND'
```

I tried this on both docker 1.12-rc2 on Mac and 1.11.2 on Ubuntu 16.04 server. Same result.

Here is my docker info:

```
$ docker info                                                                                                  
Containers: 17
 Running: 1
 Paused: 0
 Stopped: 16
Images: 72
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 263
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.14-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: 7TAC:CSUC:6DR4:EZ3N:EMDQ:FAHS:NFV6:YRM5:ROAF:CH3F:ENBP:ANWT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 42
 Goroutines: 67
 System Time: 2016-07-04T04:51:47.379162935Z
 EventsListeners: 10
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

### PR DESCRIPTION
**Pull request by twang2218**
Fix #250

Signed-off-by: Tao Wang <twang2218@gmail.com>

### CODE REVIEW

**Comment by twang2218** [comment]
Ok, back to the original problem, it's because there is no `/var/run/apache2/` and `/var/run/lock/apache2` directories, so how about we create those directories during the runtime?

I changed my PR to creating and setup permissions on `$APACHE_RUN_DIR` and `$APACHE_LOCK_DIR` in `apache2-forground`:

```bash
# setup directories and permissions
mkdir -p /run/lock
for dir in ${APACHE_RUN_DIR} ${APACHE_LOCK_DIR}
do
	mkdir -p ${dir}
	chown -R "$APACHE_RUN_USER:$APACHE_RUN_GROUP" "$dir"
done
```

**Comment by twang2218** [comment]
ping @tianon

**Comment by twang2218** [comment]
Any updates?

**Comment by tianon** [comment]
Before:
```console
$ updog --tmpfs /run php:7-apache
AH00526: Syntax error on line 74 of /etc/apache2/apache2.conf:
Invalid Mutex directory in argument file:/var/lock/apache2
```
After:
```console
$ updog --tmpfs /run 7ecd801f4282
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.14. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.14. Set the 'ServerName' directive globally to suppress this message
[Thu Jan 26 00:27:51.493503 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/7.1.1 configured -- resuming normal operations
[Thu Jan 26 00:27:51.493548 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Pull request merged**
