### PR TITLE
Add PHP 7.1.0RC1

### LINKED ISSUE #277: Releasing images for PHP 7.1 beta
I am wondering if you could release images for the beta versions of PHP 7.1? I suspect that much more people would help testing it this way.

### PR DESCRIPTION
**Pull request by tianon**
See https://secure.php.net/archive/2016.php#id2016-09-01-1

Closes #277

### CODE REVIEW

**Comment by tianon** [comment]
Easier diff:
```diff
commit ce3d81c7eefbe69860a8eaf63c05db5dd7a98a8d
Author: Tianon Gravi <admwiggin@gmail.com>
Date:   Tue Sep 6 12:31:18 2016 -0700

    Add PHP 7.1.0RC1

diff --git a/.travis.yml b/.travis.yml
index 074a34f..aa985b9 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,6 +2,13 @@ language: bash
 services: docker
 
 env:
+  - VERSION=7.1 VARIANT=
+  - VERSION=7.1 VARIANT=alpine
+  - VERSION=7.1 VARIANT=apache
+  - VERSION=7.1 VARIANT=fpm
+  - VERSION=7.1 VARIANT=fpm/alpine
+  - VERSION=7.1 VARIANT=zts
+  - VERSION=7.1 VARIANT=zts/alpine
   - VERSION=7.0 VARIANT=
   - VERSION=7.0 VARIANT=alpine
   - VERSION=7.0 VARIANT=apache
diff --git a/Dockerfile-debian.template b/7.1/Dockerfile
similarity index 85%
copy from Dockerfile-debian.template
copy to 7.1/Dockerfile
index 49020f9..a58401f 100644
--- a/Dockerfile-debian.template
+++ b/7.1/Dockerfile
@@ -1,3 +1,9 @@
+#
+# NOTE: THIS DOCKERFILE IS GENERATED VIA "update.sh"
+#
+# PLEASE DO NOT EDIT IT DIRECTLY.
+#
+
 FROM debian:jessie
 
 # persistent / runtime deps
@@ -26,17 +32,15 @@ RUN mkdir -p $PHP_INI_DIR/conf.d
 ##<autogenerated>##
 ##</autogenerated>##
 
-ENV GPG_KEYS %%GPG_KEYS%%
+ENV GPG_KEYS A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0
 
-ENV PHP_VERSION %%PHP_VERSION%%
-ENV PHP_FILENAME %%PHP_FILENAME%%
-ENV PHP_SHA256 %%PHP_SHA256%%
+ENV PHP_VERSION 7.1.0RC1
+ENV PHP_FILENAME php-7.1.0RC1.tar.xz
 
 RUN set -xe \
 	&& cd /usr/src \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz \
-	&& echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c - \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME" -o php.tar.xz \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME.asc" -o php.tar.xz.asc \
 	&& export GNUPGHOME="$(mktemp -d)" \
 	&& for key in $GPG_KEYS; do \
 		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
diff --git a/Dockerfile-alpine.template b/7.1/alpine/Dockerfile
similarity index 88%
copy from Dockerfile-alpine.template
copy to 7.1/alpine/Dockerfile
index 623a133..8f78188 100644
--- a/Dockerfile-alpine.template
+++ b/7.1/alpine/Dockerfile
@@ -1,3 +1,9 @@
+#
+# NOTE: THIS DOCKERFILE IS GENERATED VIA "update.sh"
+#
+# PLEASE DO NOT EDIT IT DIRECTLY.
+#
+
 FROM alpine:3.4
 
 # persistent / runtime deps
@@ -31,20 +37,18 @@ RUN mkdir -p $PHP_INI_DIR/conf.d
 ##<autogenerated>##
 ##</autogenerated>##
 
-ENV GPG_KEYS %%GPG_KEYS%%
+ENV GPG_KEYS A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0
 
-ENV PHP_VERSION %%PHP_VERSION%%
-ENV PHP_FILENAME %%PHP_FILENAME%%
-ENV PHP_SHA256 %%PHP_SHA256%%
+ENV PHP_VERSION 7.1.0RC1
+ENV PHP_FILENAME php-7.1.0RC1.tar.xz
 
 RUN set -xe \
 	&& apk add --no-cache --virtual .fetch-deps \
 		gnupg \
 	&& mkdir -p /usr/src \
 	&& cd /usr/src \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz \
-	&& echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c - \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME" -o php.tar.xz \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME.asc" -o php.tar.xz.asc \
 	&& export GNUPGHOME="$(mktemp -d)" \
 	&& for key in $GPG_KEYS; do \
 		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
diff --git a/docker-php-ext-configure b/7.1/alpine/docker-php-ext-configure
similarity index 100%
copy from docker-php-ext-configure
copy to 7.1/alpine/docker-php-ext-configure
diff --git a/docker-php-ext-enable b/7.1/alpine/docker-php-ext-enable
similarity index 100%
copy from docker-php-ext-enable
copy to 7.1/alpine/docker-php-ext-enable
diff --git a/docker-php-ext-install b/7.1/alpine/docker-php-ext-install
similarity index 100%
copy from docker-php-ext-install
copy to 7.1/alpine/docker-php-ext-install
diff --git a/docker-php-source b/7.1/alpine/docker-php-source
similarity index 100%
copy from docker-php-source
copy to 7.1/alpine/docker-php-source
diff --git a/7.0/apache/Dockerfile b/7.1/apache/Dockerfile
similarity index 90%
copy from 7.0/apache/Dockerfile
copy to 7.1/apache/Dockerfile
index fedb32a..6c9ca4d 100644
--- a/7.0/apache/Dockerfile
+++ b/7.1/apache/Dockerfile
@@ -88,17 +88,15 @@ ENV PHP_EXTRA_BUILD_DEPS apache2-dev
 ENV PHP_EXTRA_CONFIGURE_ARGS --with-apxs2
 ##</autogenerated>##
 
-ENV GPG_KEYS 1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763
+ENV GPG_KEYS A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0
 
-ENV PHP_VERSION 7.0.10
-ENV PHP_FILENAME php-7.0.10.tar.xz
-ENV PHP_SHA256 348476ff7ba8d95a1e28e1059430c10470c5f8110f6d9133d30153dda4cdf56a
+ENV PHP_VERSION 7.1.0RC1
+ENV PHP_FILENAME php-7.1.0RC1.tar.xz
 
 RUN set -xe \
 	&& cd /usr/src \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz \
-	&& echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c - \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME" -o php.tar.xz \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME.asc" -o php.tar.xz.asc \
 	&& export GNUPGHOME="$(mktemp -d)" \
 	&& for key in $GPG_KEYS; do \
 		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
diff --git a/7.0/apache/apache2-foreground b/7.1/apache/apache2-foreground
similarity index 100%
copy from 7.0/apache/apache2-foreground
copy to 7.1/apache/apache2-foreground
diff --git a/docker-php-ext-configure b/7.1/apache/docker-php-ext-configure
similarity index 100%
copy from docker-php-ext-configure
copy to 7.1/apache/docker-php-ext-configure
diff --git a/docker-php-ext-enable b/7.1/apache/docker-php-ext-enable
similarity index 100%
copy from docker-php-ext-enable
copy to 7.1/apache/docker-php-ext-enable
diff --git a/docker-php-ext-install b/7.1/apache/docker-php-ext-install
similarity index 100%
copy from docker-php-ext-install
copy to 7.1/apache/docker-php-ext-install
diff --git a/docker-php-source b/7.1/apache/docker-php-source
similarity index 100%
copy from docker-php-source
copy to 7.1/apache/docker-php-source
diff --git a/docker-php-ext-configure b/7.1/docker-php-ext-configure
similarity index 100%
copy from docker-php-ext-configure
copy to 7.1/docker-php-ext-configure
diff --git a/docker-php-ext-enable b/7.1/docker-php-ext-enable
similarity index 100%
copy from docker-php-ext-enable
copy to 7.1/docker-php-ext-enable
diff --git a/docker-php-ext-install b/7.1/docker-php-ext-install
similarity index 100%
copy from docker-php-ext-install
copy to 7.1/docker-php-ext-install
diff --git a/docker-php-source b/7.1/docker-php-source
similarity index 100%
copy from docker-php-source
copy to 7.1/docker-php-source
diff --git a/7.0/fpm/Dockerfile b/7.1/fpm/Dockerfile
similarity index 89%
copy from 7.0/fpm/Dockerfile
copy to 7.1/fpm/Dockerfile
index 743ceb5..cdda33d 100644
--- a/7.0/fpm/Dockerfile
+++ b/7.1/fpm/Dockerfile
@@ -33,17 +33,15 @@ RUN mkdir -p $PHP_INI_DIR/conf.d
 ENV PHP_EXTRA_CONFIGURE_ARGS --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data
 ##</autogenerated>##
 
-ENV GPG_KEYS 1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763
+ENV GPG_KEYS A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0
 
-ENV PHP_VERSION 7.0.10
-ENV PHP_FILENAME php-7.0.10.tar.xz
-ENV PHP_SHA256 348476ff7ba8d95a1e28e1059430c10470c5f8110f6d9133d30153dda4cdf56a
+ENV PHP_VERSION 7.1.0RC1
+ENV PHP_FILENAME php-7.1.0RC1.tar.xz
 
 RUN set -xe \
 	&& cd /usr/src \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz \
-	&& echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c - \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME" -o php.tar.xz \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME.asc" -o php.tar.xz.asc \
 	&& export GNUPGHOME="$(mktemp -d)" \
 	&& for key in $GPG_KEYS; do \
 		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
diff --git a/7.0/fpm/alpine/Dockerfile b/7.1/fpm/alpine/Dockerfile
similarity index 90%
copy from 7.0/fpm/alpine/Dockerfile
copy to 7.1/fpm/alpine/Dockerfile
index 6079caf..99a2429 100644
--- a/7.0/fpm/alpine/Dockerfile
+++ b/7.1/fpm/alpine/Dockerfile
@@ -38,20 +38,18 @@ RUN mkdir -p $PHP_INI_DIR/conf.d
 ENV PHP_EXTRA_CONFIGURE_ARGS --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data
 ##</autogenerated>##
 
-ENV GPG_KEYS 1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763
+ENV GPG_KEYS A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0
 
-ENV PHP_VERSION 7.0.10
-ENV PHP_FILENAME php-7.0.10.tar.xz
-ENV PHP_SHA256 348476ff7ba8d95a1e28e1059430c10470c5f8110f6d9133d30153dda4cdf56a
+ENV PHP_VERSION 7.1.0RC1
+ENV PHP_FILENAME php-7.1.0RC1.tar.xz
 
 RUN set -xe \
 	&& apk add --no-cache --virtual .fetch-deps \
 		gnupg \
 	&& mkdir -p /usr/src \
 	&& cd /usr/src \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz \
-	&& echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c - \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME" -o php.tar.xz \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME.asc" -o php.tar.xz.asc \
 	&& export GNUPGHOME="$(mktemp -d)" \
 	&& for key in $GPG_KEYS; do \
 		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
diff --git a/docker-php-ext-configure b/7.1/fpm/alpine/docker-php-ext-configure
similarity index 100%
copy from docker-php-ext-configure
copy to 7.1/fpm/alpine/docker-php-ext-configure
diff --git a/docker-php-ext-enable b/7.1/fpm/alpine/docker-php-ext-enable
similarity index 100%
copy from docker-php-ext-enable
copy to 7.1/fpm/alpine/docker-php-ext-enable
diff --git a/docker-php-ext-install b/7.1/fpm/alpine/docker-php-ext-install
similarity index 100%
copy from docker-php-ext-install
copy to 7.1/fpm/alpine/docker-php-ext-install
diff --git a/docker-php-source b/7.1/fpm/alpine/docker-php-source
similarity index 100%
copy from docker-php-source
copy to 7.1/fpm/alpine/docker-php-source
diff --git a/docker-php-ext-configure b/7.1/fpm/docker-php-ext-configure
similarity index 100%
copy from docker-php-ext-configure
copy to 7.1/fpm/docker-php-ext-configure
diff --git a/docker-php-ext-enable b/7.1/fpm/docker-php-ext-enable
similarity index 100%
copy from docker-php-ext-enable
copy to 7.1/fpm/docker-php-ext-enable
diff --git a/docker-php-ext-install b/7.1/fpm/docker-php-ext-install
similarity index 100%
copy from docker-php-ext-install
copy to 7.1/fpm/docker-php-ext-install
diff --git a/docker-php-source b/7.1/fpm/docker-php-source
similarity index 100%
copy from docker-php-source
copy to 7.1/fpm/docker-php-source
diff --git a/7.0/zts/Dockerfile b/7.1/zts/Dockerfile
similarity index 84%
copy from 7.0/zts/Dockerfile
copy to 7.1/zts/Dockerfile
index 89769b3..636b445 100644
--- a/7.0/zts/Dockerfile
+++ b/7.1/zts/Dockerfile
@@ -33,17 +33,15 @@ RUN mkdir -p $PHP_INI_DIR/conf.d
 ENV PHP_EXTRA_CONFIGURE_ARGS --enable-maintainer-zts
 ##</autogenerated>##
 
-ENV GPG_KEYS 1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763
+ENV GPG_KEYS A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0
 
-ENV PHP_VERSION 7.0.10
-ENV PHP_FILENAME php-7.0.10.tar.xz
-ENV PHP_SHA256 348476ff7ba8d95a1e28e1059430c10470c5f8110f6d9133d30153dda4cdf56a
+ENV PHP_VERSION 7.1.0RC1
+ENV PHP_FILENAME php-7.1.0RC1.tar.xz
 
 RUN set -xe \
 	&& cd /usr/src \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz \
-	&& echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c - \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME" -o php.tar.xz \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME.asc" -o php.tar.xz.asc \
 	&& export GNUPGHOME="$(mktemp -d)" \
 	&& for key in $GPG_KEYS; do \
 		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
diff --git a/7.0/zts/alpine/Dockerfile b/7.1/zts/alpine/Dockerfile
similarity index 87%
copy from 7.0/zts/alpine/Dockerfile
copy to 7.1/zts/alpine/Dockerfile
index bc63bd9..5be7064 100644
--- a/7.0/zts/alpine/Dockerfile
+++ b/7.1/zts/alpine/Dockerfile
@@ -38,20 +38,18 @@ RUN mkdir -p $PHP_INI_DIR/conf.d
 ENV PHP_EXTRA_CONFIGURE_ARGS --enable-maintainer-zts
 ##</autogenerated>##
 
-ENV GPG_KEYS 1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763
+ENV GPG_KEYS A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0
 
-ENV PHP_VERSION 7.0.10
-ENV PHP_FILENAME php-7.0.10.tar.xz
-ENV PHP_SHA256 348476ff7ba8d95a1e28e1059430c10470c5f8110f6d9133d30153dda4cdf56a
+ENV PHP_VERSION 7.1.0RC1
+ENV PHP_FILENAME php-7.1.0RC1.tar.xz
 
 RUN set -xe \
 	&& apk add --no-cache --virtual .fetch-deps \
 		gnupg \
 	&& mkdir -p /usr/src \
 	&& cd /usr/src \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz \
-	&& echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c - \
-	&& curl -fSL "https://secure.php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME" -o php.tar.xz \
+	&& curl -fSL "https://downloads.php.net/~davey/$PHP_FILENAME.asc" -o php.tar.xz.asc \
 	&& export GNUPGHOME="$(mktemp -d)" \
 	&& for key in $GPG_KEYS; do \
 		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
diff --git a/docker-php-ext-configure b/7.1/zts/alpine/docker-php-ext-configure
similarity index 100%
copy from docker-php-ext-configure
copy to 7.1/zts/alpine/docker-php-ext-configure
diff --git a/docker-php-ext-enable b/7.1/zts/alpine/docker-php-ext-enable
similarity index 100%
copy from docker-php-ext-enable
copy to 7.1/zts/alpine/docker-php-ext-enable
diff --git a/docker-php-ext-install b/7.1/zts/alpine/docker-php-ext-install
similarity index 100%
copy from docker-php-ext-install
copy to 7.1/zts/alpine/docker-php-ext-install
diff --git a/docker-php-source b/7.1/zts/alpine/docker-php-source
similarity index 100%
copy from docker-php-source
copy to 7.1/zts/alpine/docker-php-source
diff --git a/docker-php-ext-configure b/7.1/zts/docker-php-ext-configure
similarity index 100%
copy from docker-php-ext-configure
copy to 7.1/zts/docker-php-ext-configure
diff --git a/docker-php-ext-enable b/7.1/zts/docker-php-ext-enable
similarity index 100%
copy from docker-php-ext-enable
copy to 7.1/zts/docker-php-ext-enable
diff --git a/docker-php-ext-install b/7.1/zts/docker-php-ext-install
similarity index 100%
copy from docker-php-ext-install
copy to 7.1/zts/docker-php-ext-install
diff --git a/docker-php-source b/7.1/zts/docker-php-source
similarity index 100%
copy from docker-php-source
copy to 7.1/zts/docker-php-source
diff --git a/update.sh b/update.sh
index 9f712b0..ba4c195 100755
--- a/update.sh
+++ b/update.sh
@@ -2,6 +2,10 @@
 set -e
 
 declare -A gpgKeys=(
+	# https://wiki.php.net/todo/php71
+	# davey
+	[7.1]='A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0'
+
 	# https://wiki.php.net/todo/php70
 	# ab
 	[7.0]='1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763'
```

**Comment by tianon** [comment]
Once it's officially released, `update.sh` will pick it up automatically and replace these hacks with the real deal. :+1:

**Comment by tianon** [comment]
To generate the initial version of this, I copied `7.0/` over to `7.1/`, manually hacked my local `update.sh` to think `7.1`'s `fullVersion` was `7.1.0RC1`, then ran something like the following:
```console
$ find 7.1 -name Dockerfile -exec sed -ri '/PHP_SHA256/d' '{}' +
$ find 7.1 -name Dockerfile -exec sed -ri 's!https://secure.php.net/get/\$PHP_FILENAME/from/this/mirror!https://downloads.php.net/~davey/$PHP_FILENAME!g' '{}' +
$ find 7.1 -name Dockerfile -exec sed -ri 's!https://secure.php.net/get/\$PHP_FILENAME.asc/from/this/mirror!https://downloads.php.net/~davey/$PHP_FILENAME.asc!g' '{}' +
```

**Comment by tianon** [comment]
(I really wish upstream would treat at least RCs as first-class citizens
and put them on the mirrors like a regular release, but I suppose that's
wishful thinking at this point. :innocent: )

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
