### PR TITLE
Update to 7.2.15 && 7.3.2

### PR DESCRIPTION
**Pull request by ottnorml**

### CODE REVIEW

**Comment by deguif** [comment]
Any chance to get this merged quickly?

**Comment by ottnorml** [comment]
@deguif,
the @docker-library-bot already updated the repo (see https://github.com/docker-library/php/commit/3c64c61733a19863c5283f3f336add33dd298eeb and https://github.com/docker-library/php/commit/52c62d3afbb0c94f3727aba946de619c6c3bf6e0).
@tianon could you please update the official repo.

**Comment by phy25** [comment]
Looks like this is a non-security related bugfix release. I believe the repo will be updated eventually, but not that rush.

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/pull/5422

**Pull request closed without merging**
