### PR TITLE
Update PHP 5.6.12, 5.5.28 and 5.4.44

### PR DESCRIPTION
**Pull request by thaJeztah**
Update announcement:
http://php.net/archive/2015.php#id2015-08-06-4

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

**Comment by yosifkit** [comment]
It seems `5.5` has changed signers: https://travis-ci.org/docker-library/php/jobs/74572760#L724-L725. The documentation does not yet mention this new signer (http://www.php.net/downloads.php).

```console
# gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 5DA04B5D
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 5DA04B5D from hkp server ha.pool.sks-keyservers.net
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 5DA04B5D: public key "Stanislav Malyshev (PHP key) <smalyshev@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
# gpg --fingerprint 5DA04B5D
pub   2048D/5DA04B5D 2012-03-19
      Key fingerprint = F382 5282 6ACD 957E F380  D39F 2F79 56BC 5DA0 4B5D
uid                  Stanislav Malyshev (PHP key) <smalyshev@gmail.com>
uid                  Stanislav Malyshev (PHP key) <stas@php.net>
uid                  Stanislav Malyshev (PHP key) <smalyshev@sugarcrm.com>
sub   2048g/F9F69245 2012-03-19
```

**Comment by j-schumann** [comment]
Hello, I'ld like to ask: What's the status of this update, as it contains security fixes?
While this is merged, the manifest and the docker registry still show 5.6.11 as latest version.
Is the delay due to the missing signer? There seems to be no open issue regarding this in bugs.php.net.

**Comment by yosifkit** [comment]
It is part of https://github.com/docker-library/official-images/pull/963, so it should be up later today.

**Pull request merged**
