### PR TITLE
Remove Indexes option from /var/www

### PR DESCRIPTION
**Pull request by md5**
Fixes https://github.com/docker-library/wordpress/issues/33

### CODE REVIEW

**Comment by tianon** [comment]
Don't we still want `FollowSymlinks`?

I'm +1 on `Indexes` for sure, but still a little on the fence for symlinks being disabled or enabled by default.

**Comment by md5** [comment]
It's getting `FollowSymLinks` for `/` a few lines above. You only need `Options Indexes FollowSymlinks` because `Options Indexes` would blank out any `Options` already set in a parent directory.

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
Oh :heart:

**Comment by tianon** [comment]
LGTM

**Pull request merged**
