### PR TITLE
Add CGI variant

### PR DESCRIPTION
**Pull request by TBK**
Resolution to https://github.com/docker-library/php/issues/280

An alternative to https://github.com/docker-library/php/pull/649 instead of adding CGI to the CLI images this created a whole new image.

Image comparison between Alpine 3.7 CLI and CGI images:
image

### CODE REVIEW

**Comment by tianon** [comment]
https://github.com/docker-library/php/issues/280#issuecomment-353685711

> for me, the 4-9 MB doesn't really justify making our build servers churn out additional `php:cgi` variants (since each one would have to recompile PHP from source again, and we already have way too many supported combinations), so if we were going to add this I'd be inclined to add it to `php:cli`

(Still holds true -- we currently have no less than **_43_** _unique_ supported version/variant combinations.)

**Comment by TBK** [comment]
Would adding a single image based on Alpine 3.7 be acceptable?

**Comment by tianon** [comment]
We're planning to merge #649 as soon as Travis is green, which will mean that all `-cli` variants will be exactly what's described here.

**Comment by TBK** [comment]
Oki 👍

I will close this PR then.

**Pull request closed without merging**
