### PR TITLE
Install file and re2c as required by docker-php-ext-install

### LINKED ISSUE #86: Install re2c and file ?
It seems that if I run `docker-php-ext-install anything`, re2c and file commands are always warned for their noneixstence. Perhaps it's better to install re2c and file in the Dockerfiles?

### PR DESCRIPTION
**Pull request by xuhdev**
Fix #86

### CODE REVIEW

**Comment by md5** [comment]
Did you actually test this? I thought `file` came in a package called `fileutils`.

**Comment by xuhdev** [comment]
file is [here](https://packages.debian.org/jessie/file). fileutils is a different package

**Comment by md5** [comment]
Apologies. I just tested this and it works fine and I was mistaken about `fileutils`.

**Comment by xuhdev** [comment]
It seems that the testing error does not come from the PR.

**Comment by yosifkit** [comment]
Ah, failures were just bad/slow keyservers. LGTM.

Ping @tianon

**Comment by tianon** [comment]
Rocking, they're even appropriately alphabetized. :+1:

LGTM

**Comment by xuhdev** [comment]
I actually forgot to remove the `file` installation in buildDeps, which gets uninstalled later. Do you accept another PR to fix this?

**Comment by yosifkit** [comment]
Oh, `file` is only needed during build and not for `docker-php-ext-install`?

**Comment by xuhdev** [comment]
@yosifkit file is needed for `docker-php-ext-install`, but the `buildDeps` line contains file which makes the package removed later

**Comment by tianon** [comment]
Yeah, a new PR would be fantastic! :+1:

**Comment by yosifkit** [comment]
Oh, I see. Yes a quick PR is fine :+1:.  We have not pushed the changes to `docker-library/official-images`, so there is plenty of time to fix before new images are made.

**Comment by xuhdev** [comment]
Alright, PR made #90

**Pull request merged**
