### PR TITLE
Add "--ini-name" flag to docker-php-ext-enable (especially for controlling order)

### LINKED ISSUE #173: docker-php-ext-enable: Ordering
Related to this issue: https://github.com/krakjoe/apcu-bc/issues/9#issuecomment-168378224

I want to order the apc/apcu ini files, so that apcu loads before apc.
I use docker-php-ext-enable to enable also customly build extensions.

docker-php-ext-enable should also accept an order number,
or an extra command like docker-php-ext-order be provided.

Thank you and
with best regards

### PR DESCRIPTION
**Pull request by tianon**
Fixes #173

cc @strarsis -- would you like to give this a try and make sure it works? :smile:

### CODE REVIEW

**Comment by strarsis** [comment]
On can try it out by adding this line to Dockerfile or run directly the PHP image (/bin/bash):
````
RUN curl https://raw.githubusercontent.com/infosiftr/php/ini-name/docker-php-ext-enable -o /usr/local/bin/docker-php-ext-enable
````
(Before using docker-php-ext-enable)

I just tried it out and it works nicely:
````
docker-php-ext-enable apcu --ini-name 20-docker-php-ext-apcu.ini
````

With best regards

**Comment by yosifkit** [comment]
LGTM

**Comment by yosifkit** [comment]
Thanks @strarsis!

**Comment by strarsis** [comment]
In case this is helpful: I had to use image php:7.0-fpm instead image php:7.0.0-fpm 
because image php:7.0.0-fpm doesn't use the updated script.

**Pull request merged**
